### ISSUE TITLE
Not an issue: Updated to Openelec 5.0.1, it is working with Hyperion!!

### ISSUE THREAD

**Issue by cmvac** [tvdzwan/hyperion#252] opened 2015-02-04 17:00 UTC
Just updated my Raspberry Pi B to the latest Openelec 5.0.1. I had the latest Gotham build installed and decided to update. After I did the usual manual update the ambilight responded immediately! You can change the Install on Openelec bit.

**Comment by slovdahl** [comment] 2015-02-12 15:59
I can confirm what @cmvac says, I just got my LED strip, and after I connected it to my OpenELEC 5.0.1 RPi, installed hyperion and rebooted the lights turned on!

**Comment by tpmodding** [comment] 2016-03-02 21:15
@cmvac could you close this pleasE?

**Comment by brindosch** [comment] 2016-03-08 00:31
Closed due to age. Please open a new one, if problems still exists.
Thank you

**Closed by brindosch** 2016-03-08 00:31 UTC
