### ISSUE TITLE
Ada light not working with Hyperion

### ISSUE THREAD

**Issue by Daniel6803** [tvdzwan/hyperion#461] opened 2016-01-18 19:21 UTC
Hey,

im really hoping for some advice from you guys. Im pretty sure this issue is not only hyperion related, but maybe someone has an idea whats going wrong. It feels like i read every tutorial on the planet by now, how to get an adalight to work with hyperion. But i can't get it right after all. I'm trying different things now for several days, but with nearly no success! :(
Im getting very frustrated now, because it seems quite simple in the tutorials and not many settings to try..

My Issue in short form: 
When i connect my Arduino Mega (running adalight code) to my macbook and run the colorswirl demo in processing nothing happens (Rx LED of the Mega flashes like crazy). Same thing when i try hyperion on Pi2 or the adalight code on the macbook. So normal i would guess there is a issue with the Mega or the adalight code on it, like wiring/Baudrate/wrong LED driver etc...

But if i fire up Prismatik everything runs well, LEDS light up fine. I can control the colors, screengrabbing works. So LEDs connected right to Mega.
The thing that drives me crazy is, only Prismatic works any other tool that tries to talk to the adalight keeps it dark and i can't figure out what the problem is...

I will describe my setup with a little more details now:

- Raspberry Pi2 Model B with openelec 6.0 and newest hyperion.
- Im using an Arduino Mega 2560 (possible clone) with LDP6803 (atm 50LEDs for testing purposes, will be about 600 when finished)
Pin 51 for Data, Pin 52 for Clock, GND Mega connected to GND LDP6803
Power over USB (depending on the use case from the Pi2 or Macbook)
I tried different implementations of the adalight code (and if required other pins, like Data = 2, Clock = 3)

Im using fairly old led drivers right now.. So i had to try different adalight sketches where some smart people added the LDP6803 support. 

I used this sketch from this thread. The user "Vollstrecker" (Big Thx) made it compatible with LDP6803
https://forums.adafruit.com/viewtopic.php?f=47&t=40394

(I also tried this adalight code to check if the other code is faulty: https://github.com/Hilbert70/LEDStream 
But exact same results, so moving on with the first one.)

This is the paste from the adalightcode (from Vollstrecker) im using right now:
http://pastebin.com/r0MYdizw

Any ideals why it doesn't work with hyperion or processing color swirl?
That is my hyperion config: http://pastebin.com/42HhAYQ9

Here is the paste from colorswirl: http://pastebin.com/d2s9xARs

What i found out: 
- Serialport seems to be right. same like in arduino IDE "dev/cu.usbmodem1411"
- when i run the code, the Rx LED on the Mega goes bonkers and i get about 70-80 fps in processing. (is this crazy flashing correct, even if there shouldn't be any data to send atm?)
if i set a different port nothing lights up and i get about 32000.... fps.
- in the adalight code it states if there is no data received "Ada" is written to the serial port every 1sec.
So when the wrong port is selected Tx flashed about every second
So i asume i got the port right. moving on..
- i set the baudrate on both at 115200 for now... if i set it to something different nothing changes. i keep it same on both ends.

So when the connection is working assumed that maybe i got the LED count high/low byte count wrong... 
BUT as far as i understand, this fine code looks for magic word "Ada" then the LED count is checked and the checksum is verified. Then the led count is used to set the number of LEDs to drive. So no calculating by hand. Errors with mismatching LED counts should not be possible (very nice).

But when the magic word "Ada" is received for the first time a short test pattern will be sent to the LEDs (short flashes of the 3 colors) When i connect with Prismatik this works. But with any other tool (hyperion, processing colorswirl) this never happens...

So i assume there must be something differently handled with the magic word between Prismatik and the other tools, or even the whole communication fails.

Does anyone know a tool to sniff the serial port? 
As next step, i would like to see what is the difference between Prismatik and hyperion when they send data to the adalight.

Now im out of ideals here... from my understanding it SHOULD work...
Any ideas what i am missing, or what i could try next are highly appreciated.

Thank you very much in advance. If there is any information missing, please feel free to ask!

**Comment by Petoodle** [comment] 2016-02-05 14:34
Hey,

Cheers, I've got kind of the same problem. I am not using Hyperion though, don't even know what that is to be honest. I'm just using an arduino with this ledstrip: http://www.banggood.com/5M-5050-RGB-Dream-Color-6803-IC-LED-Strip-Light-Waterproof-IP67-12V-DC-p-931386.html 

If I run this program: https://github.com/adafruit/LPD6803-RGB-Pixels/blob/master/examples/strandtest/strandtest.pde
Mentioned in this tutorial: https://learn.adafruit.com/20mm-led-pixels/code
I adapt:
int dataPin = 11;
int clockPin = 13;
and I've got no problems at all, rainbows all the way :)
The sad thing is: this does not give further instructions in how to make ambilight work.

So when I try the adalight test: https://github.com/adafruit/Adalight/blob/master/Arduino/LEDstream/LEDstream.pde
Mentioned in this tutorial: https://learn.adafruit.com/adalight-diy-ambient-tv-lighting/download-and-install
and it does'nt work. It just stays the same colour as it was before. Now in this program, the data and clockpin should be connected to the same pins I did in the test before. This shows the problem has nothing to do with wiring. But I just cant find the method to make this work.

Does anyone have an idea please?

But if I try to

**Comment by tpmodding** [comment] 2016-02-27 19:44
hey guys, did your fixed your problems or need help?

**Comment by Petoodle** [comment] 2016-02-27 20:28
I'm working on it right now actually, and I have been trying for  a few weeks. What I found out so far:
I've got another kind of ledstrip than advised. I have the 6803, while adafruit works with WS2801 ledstrips. The differences are: the microcontrollers are different. So the SPI settings don't work for me. I have also tried adapting these settings, but no possible combination is working. 

The strandtest I mentioned, is perfectly working. Now I have adapted the LEDstream file for on the arduino. It gives no errors, and my inbedded tiny strandtest works so far.
[LEDstream6803.zip](https://github.com/tvdzwan/hyperion/files/149536/LEDstream6803.zip)

The sad thing is: I found out the problem is probably in the Processing files. The working strandtest in Arduino has a tiny section in which it transfers the RGB numbers to bytes:

`// Create a 15 bit color value from R,G,B
unsigned int Color(byte r, byte g, byte b)
{
  //Take the lowest 5 bits of each value and append them end to end
  return( ((unsigned int)g & 0x1F )<<10 | ((unsigned int)b & 0x1F)<<5 | (unsigned int)r & 0x1F);
}`

Now the problem is: for ambilight the RGB are not converted to bytes in the Ledstream (Arduino) file I edited, but in the ColorSwirl and Adafruit (Processing) files: https://github.com/adafruit/Adalight

Now I have totally no clue how to adapt the Processing files so it sends the bytes in the correct sequence to the ledstrip. If it was an arduino file it would be easier: I would just copy the code above and try things. But I have no clue how to rewrite it to the Processing language, and which values in the Processing code I should transfer to bytes.

I would be so grateful if someone would help me! I've been on this for weeks (because I have very little experience with writing codes). Thank you in advance!

**Comment by Petoodle** [comment] 2016-02-27 20:36
I have also found out: I first used a fake arduino from china. It missed some drivers for a communication chip. I think that is probably Daniel6803's problem. I found that over here: https://www.youtube.com/watch?v=HHF45zhe_9U
I personally just didn't fix that problem yet, because I only want to handle one problem at once. I had a real Arduino lying around, so just continued with that one. I can open a new topic for my problem if that's better? :)

**Comment by tpmodding** [comment] 2016-02-28 02:16
could you try this code
http://pastebin.com/6N58iLX5

i have heard that the lpd8806 and lpd8803 "should" run with the same config..just give the above sketch a chance :)

**Comment by Petoodle** [comment] 2016-02-28 09:53
I tried the code. It does color my leds, but not like commanded. It is a totally random pattern of colors that just changes three times. I don't have LPD8803, but LPD6803. That is the problem. On the FAQ of FastLED:

6. Why doesn't FastLED support this random led chipset or that random MCU?
Technical - some LED chipsets we have made a decision to not directly support in the library. Primarily this includes any LED chipset that requires interrupts/timers to properly manage/control (HL1606, LPD6803). FastLED supports multiple AVR variants, as well as nearly a half dozen arm architectures (with a couple architectures that are neither ARM or AVR on the horizon as well) - each of which do interrupts and timers slightly differently. Likewise, with some MCU architectures we've made a decision to not support because of either time (msp430, for example) or because we don't feel the platform is a useful platform to try to optimize FastLED for (PIC).

So I'm afraid the FastLED library is no option for me :(

**Comment by penfold42** [comment] 2016-02-28 11:21
Why don't you reuse some of the native bit packing code from Hyperion ?

On a pi with SPI, it can do it directly:

https://github.com/tvdzwan/hyperion/blob/master/libsrc/leddevice/LedDeviceLpd6803.cpp

**Comment by Petoodle** [comment] 2016-02-28 12:02
Hi penfold42,

I'm using an arduino. I've heard the iostream library (and probably more in the code) won't work for arduino. (I know this post is in the wrong section for arduino, but I really don't know where else to ask my question.)

I really appreciate you guys are thinking with me for a solution!

**Comment by Daniel6803** [comment] 2016-02-28 12:56
Hey Guys,

thanks for interest in my problem.

@tpmodding im very grateful that you are offering your help!

@Petoodle: I was aware of the issue that the chinese try to save a few more cents and use different usb2serial converter chips without thinking consequences (duh! so chinese). I ordered one with the original chip (Atmega 16U2 not CH340G)

First the good news. After many more annoying days with try, error and port sniffing, i fixed the issue!
ambilight up and running with the LPD6803!

To be honest it was very easy in the end. 
- Baud rate, wiring, adalight code on arduino all was right from the start!

The Processing adalight codes seems to be messed up some how when it comes to sending the magic word. I gave up on this one and didn't investigate it further, because i only wanted to use it for testing purposes (bad bad idea... led only to even more confusion). I assume it sends to word right after its started, but if its started the mega is also reset. So the magic word gets lost on the way while the mega is not yet ready.. the magic word never gets send again while running. so mega receives data (Rx flashing) but no magic word inside, so no light.. Its all about the magic word and right timing. Prismatic is the only one thats sends the magic word again on some occasions like when a different mode or constant color is selected. thats why it works.

So, the solution... at some point i remembered a user commenting on one of the many ambilight tutorials that it could be necessary to add a delay for hyperion to send the magic word, to give the arduino (connected over usb) time to finishing booting. If not it could be possible, that the magic word (will only be send one time at hyperion start up) is send to the arduino boot loader and nothing further happens (Except Rx goes bonkers)... :(

As far as i remember this isn't mentioned in the Hyperion FAQ or in any of the many tutorials. And the Option is not even present in the HyperCon.jar. But in the HyperCon_ssh.jar it's included, strange!

I just looked it up again, the option is in the hyperionconfig i posted here, it was sitting directly before my eyes... set to 0. But because processing was also not working it dragged my attention in the wrong direction... 

So just set 
"delayAfterConnect"     : 0, 
to something like 5000 or 10000 and it worked.

@Petoodle: if you like i would be glad to post a step to step solution for your 6803. I think we will have it working in no time, just the right code and a few settings :)

Thanks to everyone that where willing to help, much appreciated.
Also thanks to the hyperion guys for creating such an amazing bit of software for free!

I still have a lot of config work to do.. my setup is a bit different then the common ones and requires a lot of manual config editing... ;)

2 pictures of the current status..
[URL=http://www.directupload.net/file/d/4278/xnzsgrtj_jpg.htm][IMG]http://fs5.directupload.net/images/160228/temp/xnzsgrtj.jpg[/IMG][/URL]

[URL=http://www.directupload.net/file/d/4278/rheyqnsf_jpg.htm][IMG]http://fs5.directupload.net/images/160228/temp/rheyqnsf.jpg[/IMG][/URL]

Best regards Daniel.

**Comment by tpmodding** [comment] 2016-02-28 13:05
good to hear :)

ps: f***ing awesome setup!!!!! thats amazing!!!

**Comment by Petoodle** [comment] 2016-02-28 13:07
@Daniel6803 

YES PLEASE YES GOD THANK YOU! I'll seriously kneel down before my screen and shout THANK YOU DANIEL if you please would help me :dancer:  

Thanking you SO MUCH in advance!

Your setup looks amazing! I'll post one of my setup aswell when it works :D

**Comment by Daniel6803** [comment] 2016-02-28 13:47
Hey Petoodle, im sure thats not necessary ;)

But i have to warn you, configuring an ambilight with these 15bit color LEDs is not easy, sometimes especially with mixed colors and minimal brightness the color and flip to one of the main colors, can look very ugly. better get a true 24bit color strip later. For me, im using 20m of 6803 build in the shelfs some years ago. I upgraded them recently with an arduino, so atm not willing to change the whole strip. working on a software fix... maybe like "input lower then minimum brightness --> stay off"

Okay, lets see. you got the strandtest.pde working. thats good. wiring, pins and power are okay
Now upload the Afterglow sketch i posted on the arduino.
http://pastebin.com/r0MYdizw

The beauty of this code is: it just shows the colors you at it. You send the magic word (Ada + LED count inside) Then the code reads the LED count from this. No need for manual LED calculation in arduino code. if you power the leds and the arduino up, they should be random colored, then off. if no data is send you should see the Tx LED flashing about every second (Arduino sends "Ada" to show the sender its there) if like this the arduino and led part are setup and good to go!

Later you can change the baud rate in line 122: from 115200 to 230400 (im using a MEGA if it works for you like this, just leave it) But very important sender and receiver must use the same rate!

Now to be sure you could install prismatic and see if it works with your adalight. Or you could just move on and try it with hyperion directly (i would use this tool for ambilight)

here is a tutorial how to setup the config file for hyperion:
http://ai.rs/reviews/rgb-delight-raspberry-pi2-arduino-nano-ws2812b-using-hyperion-on-openelec/

Some questions: on with device you want to run hyperion? Raspberry Pi 1 / 2 ? your PC / Mac?
With Arduino are you using?

**Comment by Petoodle** [comment] 2016-02-28 14:47
Hi Daniel,

Thank you! I'm going to try this when I get home.

I'm using my pc (windows) and an arduino uno.

I'll let you know if it works :)
Op 28 feb. 2016 14:47 schreef "Daniel6803" <notifications@github.com>:

Hey Petoodle, im sure thats not necessary ;)

But i have to warn you, configuring an ambilight with these 15bit color
LEDs is not easy, sometimes especially with mixed colors and minimal
brightness the color and flip to one of the main colors, can look very
ugly. better get a true 24bit color strip later. For me, im using 20m of
6803 build in the shelfs some years ago. I upgraded them recently with an
arduino, so atm not willing to change the whole strip. working on a
software fix... maybe like "input lower then minimum brightness --> stay
off"

Okay, lets see. you got the strandtest.pde working. thats good. wiring,
pins and power are okay
Now upload the Afterglow sketch i posted on the arduino.
http://pastebin.com/r0MYdizw

The beauty of this code is: it just shows the colors you at it. You send
the magic word (Ada + LED count inside) Then the code reads the LED count
from this. No need for manual LED calculation in arduino code. if you power
the leds and the arduino up, they should be random colored, then off. if no
data is send you should see the Tx LED flashing about every second (Arduino
sends "Ada" to show the sender its there) if like this the arduino and led
part are setup and good to go!

Later you can change the baud rate in line 122: from 115200 to 230400 (im
using a MEGA if it works for you like this, just leave it) But very
important sender and receiver must use the same rate!

Now to be sure you could install prismatic and see if it works with your
adalight. Or you could just move on and try it with hyperion directly (i
would use this tool for ambilight)

here is a tutorial how to setup the config file for hyperion:
http://ai.rs/reviews/rgb-delight-raspberry-pi2-arduino-nano-ws2812b-using-hyperion-on-openelec/

Some questions: on with device you want to run hyperion? Raspberry Pi 1 / 2
? your PC / Mac?
With Arduino are you using?

—
Reply to this email directly or view it on GitHub
<https://github.com/tvdzwan/hyperion/issues/461#issuecomment-189875056>.

**Comment by Petoodle** [comment] 2016-02-28 17:28
Hey Daniel,

I just tried the Afterglow Arduino code you mentioned. It certainly does not give the result it should yet. :(
I cant explain what it does exactly, so here are some pictures.
I started out with the ledstrip fully red (from a program I made), so it would be easier to see.
At the start the first 3-6 leds flash green and immediately switch off. Then after every 5 or so seconds a few blue leds appear mostly in combination with some leds that are turned off. The foto's are whitout steps missing what happened. No other colors appear. After this the blue just continues randomly and it never reaches the far end of the strip.

![20160228_181144](https://cloud.githubusercontent.com/assets/17084623/13380647/2d908d74-de48-11e5-9f2a-cb11be9c268e.jpg)
![20160228_181157](https://cloud.githubusercontent.com/assets/17084623/13380651/2da0ff92-de48-11e5-9f6a-09cd0927d326.jpg)
![20160228_181212](https://cloud.githubusercontent.com/assets/17084623/13380649/2d9e38b6-de48-11e5-977a-366ae78a4899.jpg)
![20160228_181243](https://cloud.githubusercontent.com/assets/17084623/13380648/2d928520-de48-11e5-8ccb-1e31194f5d9f.jpg)
![20160228_181258](https://cloud.githubusercontent.com/assets/17084623/13380643/2d8b6e7a-de48-11e5-8f05-ef34c70deda1.jpg)
![20160228_181314](https://cloud.githubusercontent.com/assets/17084623/13380644/2d8c3346-de48-11e5-86c6-72a09d5fb50c.jpg)
![20160228_181328](https://cloud.githubusercontent.com/assets/17084623/13380650/2d9faa3e-de48-11e5-8c64-b6d622f0e2d1.jpg)
![20160228_181437](https://cloud.githubusercontent.com/assets/17084623/13380646/2d8e7494-de48-11e5-83a9-b29e481ea33c.jpg)
![20160228_181533](https://cloud.githubusercontent.com/assets/17084623/13380645/2d8dd99e-de48-11e5-888e-1a0e1343a43b.jpg)

Do you have any suggestions what I might try? Thank you!

PS: I'm using arduino uno and PC (Windows 7)

**Comment by tpmodding** [comment] 2016-02-28 17:30
did you tried ambibox to test?

**Comment by Petoodle** [comment] 2016-02-28 17:33
@tpmodding no, not yet. Daniel said: If you power the leds and the arduino up, they should be random colored, then off.
That's obviously not what happened with my strip. I'm going to try ambibox right now anyway :)

**Comment by Petoodle** [comment] 2016-02-28 18:29
Okay, I tried Ambibox, and it kind offish works. The strip is white when my screen is white and it does change color when I for instance have a green screen. But, the change is really random, so the leds do not turn really green. It just does some random disco with all colors it knows including reds.

Thank you for the Ambibox tip @tpmodding :+1: 
That works.

Now, how to get the colors right is the next step. Do you have any suggestions?

**Comment by tpmodding** [comment] 2016-02-28 18:40
did you tried a video on fullscreen ? e.g. youtube? i think the "flackering" is from the aero..

**Comment by Petoodle** [comment] 2016-02-28 18:50
Yes I tried, especially when the screen gets darker it gets trippy when the leds go off, because the blue leds are still trippy like in my pictures. I think this is wat Daniel was talking about.

The overall colour seems to be al right though! I'm really happy with the progress so far! I'm going to mess a bit with the settings in this program. Maybe I can make it work a little better :)

**Comment by Daniel6803** [comment] 2016-02-28 19:27
Hey, i don't get what's happening in the pictures. But good to hear that it works some how. How did you make it all time red? Did you change the afterglow code? The green and blue in the first LEDs sounds like the test pattern but not enough LEDs set in the sender program (ambibox in your case) 

When you use ambibox does the test pattern occur? Exactly like in the video? I made a quick one for you to illustrate what I mean, sorry for the mess... If it looks like this afterglow is up&running.

https://youtu.be/A1xvq9Nf6iU

Yes, the trippy colors in dark areas it's a strip issue :(

**Comment by Petoodle** [comment] 2016-02-28 20:24
Hey, 

To make the strip red I just loaded http://pastebin.com/A5JYPZSi
into my ledstrip. I wrote it while messing around with the strandtest. If I load a new program in the arduino, it pixelfreezes, stays red until the code says otherwise.

The random thing you see in the pictures is probably the test you are talking about, only a few hundred times slower and not getting to the end of the strand. The blue leds walk across the strip, so it would be logical. 

A few other things I noticed:
Only about the first half of the ledstrip is used with Ambibox, the second half just stays the color it was before I loaded the program. Any idea how I can make sure the data goes trough all of the ledstrip before the next data flow? (I just noticed, this part was curled up before.)

**Comment by Daniel6803** [comment] 2016-02-28 21:56
I don't know ambibox, but the afterglow reads the led count out of the magic word (its the high byte low byte part in the code) and then sets it as Number of LEDs it drives. I don't know ambibox but i would guess that anywhere in the settings the LED count is set to 25 (half strip! per 10cm 1 LED driver, drives 3 LEDs Dots at once) In your RED code you set LED count to 150, you only got 50 IC Drivers (so 50 individually controllable LEDS-Sets (containing a block of 3 LEDs) in total. Doesn't change anything for testing, but be sure to set it right in the real setup ;)

One other thing to check: As soon as you load the Afterglow code it should turn all LEDs off. (Look at line 128 ff) From my knowledge its not right that they stay red after afterglow is loaded... They should stay off until the magic word is received. When the word is received along with the LED count from ambibox it should send the test pattern like in the video.

About the speed of the pattern, i noticed that less led means slower speed... maybe ambibox led count is set to 2 or 5?

Take also a look at the Tx and Rx LED on the ardunio do they behave like i wrote earlier?

**Comment by Petoodle** [comment] 2016-03-01 13:10
Okay, just to try I installed Prismatik as well. It reacts a little bit differently than ambibox, but it has one thing in common: The colours are acting weird. Overall: Green is blue and blue is green, but on the left side, some leds are doing their own thing. With the strandtest they work fine though. I've got no clue what the problem is.
![20160301_135414](https://cloud.githubusercontent.com/assets/17084623/13427625/92d0ba88-dfb5-11e5-8bb7-31e3870dfd7d.jpg)
![20160301_135354](https://cloud.githubusercontent.com/assets/17084623/13427635/9e9a0c02-dfb5-11e5-8352-be737b936ff4.jpg)
![20160301_135343](https://cloud.githubusercontent.com/assets/17084623/13427636/9fd33d78-dfb5-11e5-9c22-924643e16245.jpg)
![20160301_140344](https://cloud.githubusercontent.com/assets/17084623/13427810/a0d31c56-dfb6-11e5-8343-5cf75b92218c.jpg)
![20160301_140402](https://cloud.githubusercontent.com/assets/17084623/13427814/a5fa724c-dfb6-11e5-8dac-e40e955dff1a.jpg)

The test pattern on startup works! It looks like in the video now. The Tx and Rx behave perfectly in both Ambibox as Prismatic.

**Comment by Daniel6803** [comment] 2016-03-01 17:30
Don't worry mate, your are nearly there!

First, color orientation as to fit on both sides. Just adjust it in Afterglow. Your orientation is RBG, it should be RGB

Line 54 in afterglow:

struct RGB { unsigned char b; unsigned char r; unsigned char g; };

just change b, r, g until it looks right.

in your case i would try:
struct RGB { unsigned char g; unsigned char r; unsigned char b; };

For your second problem, the last leds don't get data how to behave... so they act random. add the right amount of LEDs (driver ICs) in prismatic and ambibox (you got 10 per meter...) when in doubt just add some more for testing.

Its the right thing to do. maybe see if the APA102 is even better for you?
And think about the Raspberry Pi2 as media center, works awesome ;)

**Comment by Petoodle** [comment] 2016-03-01 18:33
Thank you! Now the ledstrip works perfectly fine! Except for the flickering
in darker area's of course. I'll let you know if I find a solution for
that. Now everything works I must say I prefer Ambibox over Prismatik. It
has a lot more options for finetuning and capturing.

If I can't find a solution to the flickering, I'm still going to buy
another strip. I'm really happy this works though :D

2016-03-01 18:30 GMT+01:00 Daniel6803 <notifications@github.com>:

**Comment by Petoodle** [comment] 2016-03-02 16:43
I've got some bad news if you were still trying to manage the flickering by turning the leds off in the dark intervals. I've just measured the RGB values for which the strips flicker. To do this I've used Paint. I chose the color in RGB values, and used the bucket to color the image. Then click full screen (make sure to use the right ratio for your screen and image to be fullscreen). The leds will flicker if they're not happy with the RGB values ;).

So I've kept the Red and Green constant, and I measured for the blue the following intervals in which the leds flicker:

From	to
0	53
65	79
90	128
141	154
165	179
187	205
222	240

So it's sadly not as easy as: beneath this brightness, don't switch on the leds. If you still want to continue with these leds, maybe you can say: between value x and y, take value z. With z just above the interval. I'm not going to do that though. I'm going to buy a new strip. :)

**Comment by Daniel6803** [comment] 2016-03-03 07:00
Hey, thanks for trying that, very interesting find. Looks like the LEDs flicker nearly all the time. 

But, what do you mean by flickering exactly? 

For me it's in the darker areas when you go slowly to the lowest possible ON valve maybe for white. Then,  for example grenn will turn off before blue and rad, so white flips to pink before all LED turn off... So sometimes you could get a wrong color for dark scenes.

But that's because the strip had only 7 brightness steps per color. WS2801 or APA102 got 255, they have the same issues but you will most likely not see it, because much more color steps are possible.

Do you experience the same or are we taking defective lightbulb flickering? If that's the case, ambibox could cause this issues, maybe try a smoothing filter.

But yes, buy a new strip.. Saves a lot of pain to the brain ;) 
For me it's sadly not that easy, beside the costs of 20m APA102, it would take days to rip the whole tv wall apart only to change the strip. I would also have to think about how to get more LEDs to the sides, behind the milky glass. I'm not yet annoyed enough to take this step ;)

**Comment by Petoodle** [comment] 2016-03-04 14:14
Hey,

Sorry, had some busy couple of days.
I think you have a different flickering than I do. No idea what my problem is though. This is a video of whats happening: https://vid.me/DM9l
The first few seconds are a stable color, the last few seconds show a flickering color.

**Comment by Daniel6803** [comment] 2016-03-05 08:31
You do have a different issue, that looks totally weird. I can confirm it's not the fault of the led strip nor the afterglow code. Never have seen something like this. Prismatic doing the same thing? Would be unfortunate to buy a new strip to find out ambibox causes the flickering. New strip will be an upgrade of cause.

**Comment by penfold42** [comment] 2016-03-05 10:01
Is you pi over locked ?

I've seen the SPI speed changes on mine when the CPU governer kicks in.

**Comment by Petoodle** [comment] 2016-03-05 12:02
@penfold42 I don't use a raspberry pi, but pc (windows 7) :)

**Comment by brindosch** [comment] 2016-03-19 00:54
@Petoodle 
Any updates?

**Comment by Petoodle** [comment] 2016-03-19 01:41
Yeah, I tried prismatic aswel now. Both prismatic as ambilight give different glitches. I can't exactly explain what the glitches are, because it is so random. In prismatic it does not have the same intervals of colour that it glitches. And in the paint method the colours are fine, but normally used, 9/10 times it doesn't represent the colour of the screen but is pretty random. Ambibox has the weird interval glitches,  but at least is a bit consequent in that. Oudside of these intervals it does a good job.

 The startup is not as smooth as it should be yet. It was better than earlier, but it is not as smooth as in Daniels video yet. 

Not sure how to fix all that because it is all so inconsequent. 

Thanks for your interest :)

**Comment by brindosch** [comment] 2016-03-23 00:21
Due to the point it is not Hyperion related. I would suggest to close it.
@Daniel6803 @Petoodle 
How is your state?

**Comment by Petoodle** [comment] 2016-03-23 07:13
Still the same. You may close this. Thank you for all your warm help!
Op 23 mrt. 2016 01:21 schreef "brindosch" <notifications@github.com>:

**Comment by brindosch** [comment] 2016-03-23 10:25
Thank you :)

**Closed by brindosch** 2016-03-23 10:25 UTC

**Comment by Daniel6803** [comment] 2016-03-23 17:23
The issue can be closed. It's not related to hyperion. 

It's the same here. Will fine tune the settings, but it's  difficult with this strip.
