### ISSUE TITLE
Hyperion not working after OSMC updated to 2015.11-1

### ISSUE THREAD

**Issue by StoneAgeSkillz** [tvdzwan/hyperion#416] opened 2015-11-30 20:00 UTC
Hi, i'm using Hyperion on RPi B with OSMC and WS2812b. After last update to 2015.11-1, Hyperion stoped working.
Today was another update(2015.11-2). I have tryed to reinstall, but with no success.
After checking thru installation i found this in boot/config.txt: 

dtoverlay=lirc-rpi:gpio_out_pin=17,gpio_in_pin=18

I've disabled it since it uses the same pin as hyperion and added dtparam=spi=on again.
But still no success to get it working.

Please, help.

**Comment by b2un0** [comment] 2015-12-01 12:49
this is my config.txt and it works like an charm after the last update (yesterday)

```
dtoverlay=lirc-rpi:gpio_out_pin=17,gpio_in_pin=18
hdmi_ignore_cec=0
over_voltage=0
over_voltage_sdram=0
force_turbo=0
disable_splash=1
dtparam=spi=on
start_x=1
avoid_warnings=1
max_usb_current=1
sdtv_aspect=1
hdmi_force_hotplug=1
hdmi_ignore_cec_init=1
```

**Comment by StoneAgeSkillz** [comment] 2015-12-01 19:26
Just did a clear OSMC install. Then Hyperion, checked if it's running. Uploaded config. Hyperion restart. And nothing. More than once.

Do you use WS2812B as well? On which pin? Does this lirc pin mean pin 18 or GPIO18?

**Comment by penfold42** [comment] 2015-12-03 07:48
It means gpio18, not pin 18 on the header.

**Comment by StoneAgeSkillz** [comment] 2015-12-03 15:29
I'm done with it. Tryied it more than 5 times from clear install. Nothing worked. Instaled once on 2015.10-1. Worked on first try. Didn't even needed that dtparam=spi=on. And lirc is still there.
Strange that it's on pin 12 (GPIO18), same as LIRC.
If enyone knows how to get it working after update, let me know.

**Comment by penfold42** [comment] 2015-12-03 20:28
You've not provided much info :

What hardware are you using ?
What led type are you using ?
Does Hyperion give any errors when you restart it from the command line ?
Does the kernel dmeag have any related errors ?

**Comment by StoneAgeSkillz** [comment] 2015-12-03 21:22
I did: RPi B with OSMC, WS2812b with level converter and 300Ohm resistor on pin12 (GPIO18).
Since it works flawllesly on 2015.10-1, we can sort wiring and config errors out.  Sometimes, when i  try to restart hyperion, it can't shutdown. It says "stoping" and then "already running". Still, after reboot it should load new config, but it doesn't work. I think something is using that pin, but since i disabled LIRC (which used GPIO18) i dont know what. 
  
I give it another try over weekend, if i find some spare time. Then i post, what it did.

**Comment by Zappatron** [comment] 2015-12-04 10:39
I haven't had time to do any investigation yet but I have the exact same problem @StoneAgeSkillz. Worked fine until the November update broke it.

Must be something to do with GPIO18.

**Comment by StoneAgeSkillz** [comment] 2015-12-07 10:49
So i had little time over the weekend, but this morning i found some. So here we go:
installation: http://pastebin.com/tSjta6SH
dmesg: http://pastebin.com/kEeGSvVv

Added dtparam=spi=on, deleted lirc line, rebooted RPi. Still no succes. I think something is blocking GPIO18. Is i wrote, it works flawless on 2015.10-1.

**Comment by penfold42** [comment] 2015-12-07 11:56
[   16.647275] lirc_rpi: auto-detected active low receiver on GPIO pin 18

You could change the Lirc config to use another gpio

**Comment by StoneAgeSkillz** [comment] 2015-12-07 12:17
I'm using tvs remote via HDMI. I dont need lirc, so i have deleted its entry in /boot/config.txt. There is no lirc line in dmesg after reboot anymore.

**Comment by thewsz** [comment] 2015-12-09 16:41
Hi,
I seem to be having the same issue: OSMC + RPi2 + WS2812b. After an OSMC upgrade (not sure what it was exactly but it requested a restart) yesterday,  the LEDs just stopped working.

I've reinstalled Hyperion, then entire OSMC using the latest version, then using older OSMC images, then different combinations in config.txt ... I also checked the leds with arduino and the wiring - they're all fine.

My wiring setup is: a separate PSU for the LEDs and the RPi, with sharing the LEDs' ground to Rpi and with RPi's GPIO18 connected to the LEDs through a small resistor. This had worked since September..

[hyperion.config.json.txt](https://github.com/tvdzwan/hyperion/files/57026/hyperion.config.json.txt)
[config.txt](https://github.com/tvdzwan/hyperion/files/57030/config.txt)
[dmesg.txt](https://github.com/tvdzwan/hyperion/files/57036/dmesg.txt)
[hyperion.log.txt](https://github.com/tvdzwan/hyperion/files/57034/hyperion.log.txt)

Please advise because after some teen hours of trying different things, I'm simply out of ideas :(

**Comment by StoneAgeSkillz** [comment] 2015-12-10 18:35
Found this: https://discourse.osmc.tv/t/hyperion-with-ws2812b-not-working-after-latest-updates/10844/2

**Comment by Tester0815** [comment] 2015-12-11 17:30
rpi2 OSMC actual Version: 2015.11-1 works for me again.. 
http://download.osmc.tv/installers/diskimages/OSMC_TGT_rbp2_20151129.img.gz
I made a clean install again.. 
I saw that the update is not cleaning up...old version of kernel were on boot...

**Comment by penfold42** [comment] 2015-12-11 22:24
What is your uname -a output ?

Mine hasn't been updated for a few days :
root@rpi512:~# uname -a
Linux rpi512.home 4.2.3-3-osmc #1 PREEMP
T Tue Oct 13 17:58:31 UTC 2015 armv6l GN
U/Linux

**Comment by Tester0815** [comment] 2015-12-12 07:29
osmc@rp2OSMC:~$ uname -a
Linux rp2OSMC 4.2.3-2-osmc #1 SMP PREEMPT Mon Oct 12 01:58:40 UTC 2015 armv7l GNU/Linux

**Comment by StoneAgeSkillz** [comment] 2015-12-12 08:48
Linux osmc 4.3.0-10-osmc #1 PREEMPT Sun Nov 29 17:03:54 UTC 2015 armv6l GNU/Linux
OSMC November 2015.11-2

Still not working. U can copy spidev, like the post fron @thewsz on SOMC forum suggest, or wait for update. I've downgraded and waiting.

**Comment by penfold42** [comment] 2015-12-12 22:27
That fix is for people using SPI interface - this is normally used with ws2801 LEDs.

Gpio18 is used for the PWM support which is what I think you're using.

**Comment by thewsz** [comment] 2015-12-16 21:57
I've been able to confirm for 100% :) that the cables and the LED's are fine (used arduino for testing). Either the PWM generator is broken in my RPi (interestingly enough just after an OSMC upgrade..) or something is messed with the latest software.

I'll try another distro to check..

**Comment by thewsz** [comment] 2015-12-16 22:34
So.. I've downloaded https://github.com/pimoroni/unicorn-hat/tree/master/python/rpi-ws281x built it and installed. Then I grabbed https://github.com/jgarff/rpi_ws281x.git and ran examples/strandtest.py - the LEDs started blinking, switching etc. all nicely.

My RPi is all sane - something must have got broken with the latest version of the libs used by Hyperion.

**Comment by thewsz** [comment] 2016-01-06 12:01
Flying completely blind - I just tried compiling hyperion from all the forks mentioned in https://github.com/tvdzwan/hyperion/issues/6#issuecomment-98346522 - no luck with any of the 3.

**Comment by Zappatron** [comment] 2016-01-06 12:13
@thewsz I was using my fork fine until the November OSMC update, which broke it. Apart from a little cursory investigation of the obvious I've not had time to look at it further.

One solution would be to use OSMC from October and disable updating.

**Comment by StoneAgeSkillz** [comment] 2016-01-06 18:23
So did i. Let's see how the next update will turn.

**Comment by thewsz** [comment] 2016-01-09 00:58
@Zappatron unfortunately, I need to update or I can't install the QT4 libs as described in the hyperion installation instructions. It didn't work.

**Comment by trackdork** [comment] 2016-02-14 18:11
@thewsz i am stuck at this exact same point, though i am new to this project and don't have a previously known-good-config to fall back on.  i wonder what's going on, have you made any discoveries?  i'm afraid i'm going to have to fall back to putting an arduino in the loop - i get nothing whatsoever on GPIO18, looks to be grounded always.

**Comment by brindosch** [comment] 2016-02-18 00:14
Is this problem still present with the latest Jan 2016 release?

**Comment by trackdork** [comment] 2016-02-18 16:14
As near as I can tell, yes.  I had to go with the Adalight solution.  Works fine for the moment, the refresh rate is totally acceptable... although the additional single point of failure is probably not something I'm going to want long-term.  Once I finalize the project I can check back in to direct-drive of the WS2812 strip.

**Comment by markwal** [comment] 2016-03-01 23:01
Since the ws2811, ws2812, ws2812b's are all one signal wire strings, it reads the bit separation based on timing. The hack for doing this from jgarff is to use DMA to PWM to produce the correct timing on the gpio wire.

This approach is clever, but has a high reliance on the underlying machine staying compatible which is why it broke on the RPi2.  I suspect there is also something about the system configuration that can mess this up as well.  At the moment neither the RetroPie image (3.4) nor the OSMC image (rbp2_20160130) appear to work with ws281x out of the box.  However, latest jessie lite (2016-02-09) seems to work just fine.

My guess is that some desired configuration for retropie/osmc conflicts with this DMA/PWM technique for the LEDs.  Perhaps it is overclocking, video memory setting or perhaps some included by default driver (touch screen maybe?) that conflicts.

It does look like the problem is the timing gets all messed up because the LEDs are getting data, they just appear to be getting the wrong data.

**Comment by markwal** [comment] 2016-03-01 23:24
Hooking it up to an oscilloscope.  The bits look ok (reasonable pulse width), but too far apart.  About 10x too far apart.  It should be a 800kbps signal, but it's only putting out about 75kbps.

**Comment by brindosch** [comment] 2016-03-01 23:29
This is a interesting finding. Maybe you could ask the osmc devs what is going on?

**Comment by brindosch** [comment] 2016-03-01 23:47
Just for testing. How old is your Hyperion image? Could you build a new one with the WS2812BPWM Enabled switch?

**Comment by markwal** [comment] 2016-03-02 02:29
I'll give it a try.  I don't really need OSMC so I was thinking I'd just use the jessie-lite image and install Hyperion on that.  I just need to wire it up to frame grab off of a composite to USB stick I have.  I was just experimenting with the LED strip beforehand and came across this thread of people having similar struggles.

**Comment by trackdork** [comment] 2016-03-02 03:42
Glad there's some more activity here.  I'd really love to get rid of adalight, although with my setup it might be more appealing to switch to using an ESP8266 and send my data over UDP and lose the cables entirely.  

https://github.com/sticilface/ESP8266-wifi

**Comment by brindosch** [comment] 2016-03-22 23:23
Please use the new WS281x device.
If you are using osmc please reinstall/update with the osmc wiki guide(!!!)
To be sure everything is setting up right you have to start the script with a arguement
`./install_hyperion.sh WS281X`

**Comment by Tester0815** [comment] 2016-03-23 12:25
Hey Brindosch, 
1. issue on OSMC on rpi2 is still there...
2. Link to wiki was not working, i corrected it...
3. Install script didn't work to add dtparam=spi=on add my fresh osmc install.
4. after manual edit of config.txt go 1.

**Comment by brindosch** [comment] 2016-03-23 12:29
So you just added the line and it is working?

**Comment by markwal** [comment] 2016-03-23 12:33
BTW The ws281x doesn't need dtparam=spi=on
OSMC out of the box has analog audio turned on which needs to be disabled or redirected, but I'll try again with my hardware later today.

**Comment by brindosch** [comment] 2016-03-23 12:36
@markwal 
yes, this was my thought, spi = spi, pwm = pwm
Would be great to know what i should add during install in config.txt

the last message was, we don´t need dtoverlay=pwm for ws281x

**Comment by penfold42** [comment] 2016-03-23 13:16
I suspect the DMA channels that are used by various distributions (and versions) is changing.

Both 2811 led drivers hit the hardware directly completely bypassing the kernel with no regard for what DMA channels might be in use.

I opened this https://github.com/jgarff/rpi_ws281x/issues/72 to try to get some clarity.

**Comment by trackdork** [comment] 2016-03-23 13:22
I'm not as up to speed on the technical details but I'm comfortable poking around on Linux and familiar with the hardware components involved.  I have at my disposal an RPi 1 B+, RPi 2, and RPi 3 if there's anything I can do to help.  Please let me know.  I'd love to get rid of my adalight for this setup.

**Comment by Tester0815** [comment] 2016-03-23 14:29
config.txt edit for include dtparam=spi=on and dtoverlay=pwm is obsolet.
The hint for activated audio to disable is there...
I can not find any config in config.txt or in the overlays, that points to that to correct that...

I disabled every dtoverlay parameter in config.txt and moved these overlay away, to make sure they are loaded centrally w/o config...
hifiberry-amp-overlay.dtb
hifiberry-dac-overlay.dtb
hifiberry-dacplus-overlay.dtb
hifiberry-digi-overlay.dtb
pps-gpio-overlay.dtb
rpi-dac-overlay.dtb
uart1-overlay.dtb
w1-gpio-overlay.dtb
w1-gpio-pullup-overlay.dtb

Nothing changed... OSMC is dead for me... no support from them

**Comment by markwal** [comment] 2016-03-23 14:45
I think penfold42 may be right. Something else is using DMA channel 5. That would match with the symptoms I was seeing.

**Comment by Tester0815** [comment] 2016-03-23 14:57
Seems to be, OpenElec with pwm dtoverlay and Raspian out of the box are working fine.
It seems OSMC specific, but tOSMC don't care, 
they are not explaining what's was changed or can be the reason.
Intentionally changed at the 201511 release and in place in every newer revision...

**Comment by penfold42** [comment] 2016-03-23 20:19
It looks like spi_bcm2835 is using DMA 4 and 5 based on 
head /sys/class/dma/dma0chan*/in_use

As best I can tell this is only an indication - it relies on either DTB or the driver marking them as used.
If something hits the hardware direct, it doesn't show up here

**Comment by penfold42** [comment] 2016-03-23 20:24
@Tester0815

Are you using hdmi or composite video ?

If composite, can you try hdmi ?

**Comment by markwal** [comment] 2016-03-24 05:06
Man, this is tricky.  My desired setup is running RetroPie with hyperion.  Starting with the RetroPie image has the same problem as OSMC.  So I thought I'd set up Hyperion on Jessie and then run the RetroPie setup scripts manually and then watch what step kills the LEDs, but, but...  It didn't happen.  If I build RetroPie myself, the LEDs work.  There must be something in the base image?  Or something not in the setup script?  I'm stumped.

**Comment by brindosch** [comment] 2016-03-24 13:20
@markwal 
This pwm thing seems really... weird
@Tester0815 
Asked you the devs for help?

**Comment by Tester0815** [comment] 2016-03-24 14:45
@brindosch 
Did you even check anything before closing this issue ?
You did not check if its working... 
Sorry, I don't understand how you approach...
Check yourself:
[https://www.google.de/search?q=osmc+hyperion&q=hyperion+site:discourse.osmc.tv](url)

**Comment by brindosch** [comment] 2016-03-24 16:15
1. I got the feedback that it is working, but this was a mistake.
2. I can´t test pwm leds
3. It is open again, just one click
Would you blame me for this? I could google myself - help is always appreciated to save time and get the right information. The mirror of the world, some people complain and others just do it and are happy and glad that they have what they have

**Comment by Tester0815** [comment] 2016-03-24 17:14
@brindosch 
Yes. Indeed. 
Please read the initial issue. 
It's ws2812b related which is indeed going over PWM.

It's not related to you, why did you close it with any crosscheck at all. That's not serious work.
You can click to close but not able to search and read.
You are stealing my time for testing because you closed the issue !!!!!!!

I wrote already:
Nothing changed... OSMC is dead for me... no support from them
If want to know why, then search for yourself...

@penfold42 
I am using HDMI.

**Comment by markwal** [comment] 2016-03-24 21:57
@Tester0815 It's very unlikely to have anything to do with hyperion.  If you just install jgarff/rpi_ws281x on osmc, it also can't properly talk to the LEDs.  There is a conflict between something in the OSMC image (and the RetroPie image and probably others) and the PWM/DMA technique used to run these single wire LEDs.  Even if we figure out what the conflict is, we'll either be changing the rpi_ws281x library or giving a workaround to remove or disable some driver in OSMC.  So the only reason that this issue is alive here is because OSMC doesn't care and @brindosch is kind.   But there's nothing to fix in hyperion.

**Closed** 2016-03-26 22:12 UTC
Labels: Feedback required

**Comment by markwal** [comment] 2016-03-26 22:24
By the way, I was able to get RetroPie to work by starting from Jessie Lite and running the RetroPie3 script.  So now I have two RetroPie builds.  One from the SD card image that can't drive the LEDs and one built using the script that does drive the LEDs.  I'm trying to compare what I ended up with to see if I can figure out what the difference is.  So far I haven't figured it out.  Their config.txt and commandline.txt are the same.  lsmod looks the same.  So I'm still stumped.

**Comment by brindosch** [comment] 2016-03-26 23:03
@markwal 
Really strange yes :+1: i hope you get an idea

**Comment by penfold42** [comment] 2016-03-27 01:10
Kernel versions ?

Kernel DMA boot option ?

DMA makred as in_use ? ( there's a series of files under /sys)

**Comment by markwal** [comment] 2016-03-27 22:37
retropie image: rp, jessie-lite image: jl

rp kernel: 4.1.20-v7+ #867 SMP Mar 23 20:12
rp originally came with 4.1.18, but I tried rpi-update and it gave me 4.1.20, but didn't change the LED behavior

jl kernel: 4.1.19-v7+ #858 SMP Mar 15 15:56
```
cd /sys
find -iname '*dma*'
```
gives the same list on both

Also, /sys/modules/dma/parameters/dmachans are the same on both (3893)
/sys/firmware/devicetree/base/soc match for both dma and pwm

Not sure what you mean by Kernel DMA boot option?
