### ISSUE TITLE
1080p problems

### ISSUE THREAD

**Issue by Vincent35** [tvdzwan/hyperion#512] opened 2016-02-25 10:33 UTC
Hello,

I'm new here, so i'm sorry if I posted this in the wrong place
I've been look all over the place but can't seem to find an answer.
At the moment I've got hyperion working, I can make a screenshot and the leds are working. BUT! when I connect my pc to a hdmi splitter (which does split 1080p) and connect the HDMI splitter to a HDMI to AV converter all I get to see is a 480p image on my monitor. I also tried connecting my ps3 but that only worked if i set the ps3 to 568p. It gives me a black screen if I set it to 720p or higher. 
My guess is that the fault is with the HDMI to AV converter. 

 PC -> HDMI splitter
 HDMI splitter ->
Output 1: Monitor
Output 2: HDMI to AV -> USBTV007

So my question is:
Does anybody els have this problem or how to solve it? so I can use 1080p content on my monitor/tv.

**Comment by tpmodding** [comment] 2016-02-25 10:37
Thats a Problem of your splitter i think. Has nothing to do with Hyperion itself. Can you try Other Splitters or just try Other sources? 

Von meinem iPhone gesendet

**Comment by Vincent35** [comment] 2016-02-25 12:02
I tried two different splitters ( a $24 and a $10), both giving the same result. I connect my pc and it shows 1080p, then I connect the raspberry and it changes to 480p. forcing my pc to something above 480p results in the leds not turning on anymore. Also tried connecting the ps3 but that gives me the same result, I even had to change the ps3 to 568p so it will show up on my monitor. I also tried giving them a power supply but that doesn't change anything.

**Comment by tpmodding** [comment] 2016-02-25 12:27
may the problem is at your hdmi2av?
can you open your splitter and check which one you have
http://imgur.com/gs0DUGp

we discussed the same problem in our forum, but it's german
http://www.forum-raspberrypi.de/Thread-hdmi2av-converter-welcher-funktioniert-wirklich-mit-loesung

**Comment by Vincent35** [comment] 2016-02-25 13:10
ah, thank you so much!!  mine is the most left one, and i got two of those -_-. Do you have any tips on getting a decent one from ebay? Or is it just gonna be a hit or miss with these things?

**Comment by garfty** [comment] 2016-02-26 09:08
I can confirm I had the exact same problem, the HDMI2AV would only output to 480p. I'm guessing there are some knock offs on Amazon and eBay, but I can confirm this one from Amazon UK http://www.amazon.co.uk/gp/product/B00A6STNHM?psc=1&redirect=true&ref_=od_aui_detailpages00 worked perfect for me.

**Comment by Vincent35** [comment] 2016-02-26 09:43
Yeah I had a feeling the HDMI2AV was the problem but wasn't sure. The link you gave doesn't seem to ship to my country. I asume you just randomly bought a new one? or did you look for something specific?
It's great to know the source of my problem!

**Comment by garfty** [comment] 2016-02-26 09:49
Ahh that sucks, sorry to hear.

I just purchased a second one, as a total last resort before giving up. I just saw other people using that type, and went for it, as I said though, I think the first one was either faulty or a knock off.

**Comment by tpmodding** [comment] 2016-02-26 10:35
http://de.aliexpress.com/item/Free-Shipping-Mini-HD-Video-Converter-Box-HDMI-to-RCA-AV-CVSB-L-R-Video-1080P/32248986965.html?isOrig=true#extend
Dont know where you live but aliexpress ships worldwide! here you cen select which one you want :)

**Comment by Vincent35** [comment] 2016-02-27 07:25
Yeah we can close it, Il try the link or look around ebay. It's good to know what's causing it. Thanks!

**Comment by tpmodding** [comment] 2016-02-27 10:57
@Vincent35 you must close it, i have no rights :)

**Closed** 2016-02-27 10:59 UTC
