### ISSUE TITLE
Last LED always flickering with RaspBerry PI2 and APA102

### ISSUE THREAD

**Issue by pcaffardi** [tvdzwan/hyperion#361] opened 2015-07-26 17:28 UTC
Hi there!
My hardware is Rpi 2 with a 3.3V->5V line buffer between the SPI port and my 98 APA102 leds. I use a 48W 5V power supply (common ground with Rpi2 power supply). I tested hyperion on Raspbian/OpenElec and RasPlex.

The problem is that all leds are working fine but the last one, always flickering, no matter the rate i set.
I tried changing the leds number configured on hyperion, or swapping the led strips, but the problem always happens on LAST LED configured on hyperion (may not be the last led of a strip).

I looked at hyperion code, and i didnt found the code where start and end frame are created for the APA102 SPI data (i use as reference this page: https://cpldcpu.wordpress.com/2014/11/30/understanding-the-apa102-superled/). I discovered a strange 500.000 ns latch delay that i dont understand, too.

I wrote a sample C program to test my configuration, that continuously sets and change all my leds. The issue i reported only happens if i dont tranfer the end frame or if i dont delay after the SPI transfer before beginning a new transfer again. 

So my question is: is there anyone experiencing the same problem? what rate are you using? what does such delay means? where are APA102 start and end frame coded in hyperion?

I'm a hacker/programmer, so i could help fixing that.

**Comment by mrgreywater** [comment] 2015-07-26 22:34
If your source is right you may want to try the following:

Replace the line https://github.com/tvdzwan/hyperion/blob/master/libsrc/leddevice/LedDeviceAPA102.cpp#L23
 with 
```cpp
const unsigned int startFrameSize = 4;
const unsigned int endFrameSize = (ledValues.size() + 63) / 64 * 4;
const unsigned int mLedCount = (ledValues.size() * 4) + startFrameSize + endFrameSize;
```
Your source states that you need at least n/2 bits for the endFrame, hyperion seems to use fixed 32 Bits for the start-frame and fixed 32 Bits for the end-frame, meaning you it's not compatible with more than 64 Leds as is.

**Comment by pcaffardi** [comment] 2015-07-27 06:16
Thank you!
I could fix that in APA102 sources but i think the start and end frame
parameters should be related to the led device and not global (fixed) SPI
parameters.
Maybe we should move all the allocation/transfer code from main hyperion
code to the led device implementation.

What about the fixed value latch delay? What does it mean?

Ciao,
Paolo Scaffardi
skype: pscaffardi
http://www.arsenio.net
http://www.sognilucidi.it

2015-07-27 0:34 GMT+02:00 mrgreywater <notifications@github.com>:

**Comment by mrgreywater** [comment] 2015-08-10 11:41
Reference #364

**Comment by pcaffardi** [comment] 2015-08-10 13:48
i'm sorry because i didnt see previous post but worked on my patch (see below), that worked fine with any pixed length. i looked at the code of previous patch, that was different by mine in end frame length computation (and documented in the linked page about APA102). My code below has been tested with any leds count up to 98.

#define MIN(a,b)	((a)<(b)?(a):(b))
#define MAX(a,b)	((a)>(b)?(a):(b))

#define APA102_START_FRAME_BYTES	4
#define APA102_LED_BYTES		4
#define APA102_END_FRAME_BITS_MIN	32
#define APA102_END_FRAME_BITS(leds)	MAX((((leds-1)/2)+1),APA102_END_FRAME_BITS_MIN)
#define APA102_END_FRAME_BYTES(leds)	(((APA102_END_FRAME_BITS(leds)-1)/8)+1)
#define APA102_LED_HEADER		0xe0
#define APA102_LED_MAX_INTENSITY	0x1f

int LedDeviceAPA102::write(const std::vector<ColorRgb> &ledValues)
{
	const unsigned int startFrameSize = APA102_START_FRAME_BYTES;
        const unsigned int ledsCount = ledValues.size() ;
        const unsigned int ledsSize = ledsCount * APA102_LED_BYTES ;
        const unsigned int endFrameBits = APA102_END_FRAME_BITS(ledsCount) ;
        const unsigned int endFrameSize = APA102_END_FRAME_BYTES(ledsCount) ;
        const unsigned int transferSize = startFrameSize + ledsSize + endFrameSize ;

	if(_ledBuffer.size() != transferSize){
		_ledBuffer.resize(transferSize, 0x00);
	} 

	unsigned idx = 0, i;
	for (i=0; i<APA102_START_FRAME_BYTES; i++) {
		_ledBuffer[idx++] = 0x00 ;
	}

	for (i=0; i<ledsCount; i++) {
		const ColorRgb& rgb = ledValues[i];

		_ledBuffer[idx++]   = APA102_LED_HEADER + APA102_LED_MAX_INTENSITY;
		_ledBuffer[idx++] = rgb.red;
		_ledBuffer[idx++] = rgb.green;
		_ledBuffer[idx++] = rgb.blue;
	}
	for(i=0; i<endFrameSize; i++)
	    _ledBuffer[idx++] = 0x00 ;

	return writeBytes(_ledBuffer.size(), _ledBuffer.data());
}

**Comment by pcaffardi** [comment] 2015-08-10 14:04
Hi! I tried answering and creating a pull request but they both
disappeared. Anyway, i tested test patch attached and it worked fine up to
98 APA102 leds, and it is what i use on my raspian/openelec hyperion
configuration.

But i have to suggest to delegate the LEDS driver to apply the brightness
parameter of HUV, because, for example, APA102 has a 5 bits brightness
parameters into the LED frame. if you scale the RGB value using the
brightness, low brightness colors are wrong. You could add a constructor
header to super LED driver, to let the driver instruct hyperion about the
brightness is used by him, and let the brightness parameter available to it
in same way.

Ciao,
Paolo Scaffardi
skype: pscaffardi
http://www.arsenio.net
http://www.sognilucidi.it

2015-08-10 13:41 GMT+02:00 mrgreywater <notifications@github.com>:

**Comment by mrgreywater** [comment] 2015-08-10 14:29
Your previous source said you should only use the full brightness (0xFF) so I don't quite understand why you changed that.

> A start frame of 32 zero bits (<0x00> <0x00> <0x00> <0x00>)
> A 32 bit LED frame for each LED in the string (<0xE0+brightness> <blue> <green> <red>)
> An end frame consisting of at least (n/2) bits of 1, where n is the number of LEDs in the string.
> Unlike the WS2812 protocol, no waiting period is required before the next update. As discussed before, I strongly suggest to only use the full brightness setting (31) to reduce flicker.

These two loops are completly irrelevant, since the data is initialized with zeros.
´´´
for (i=0; i<APA102_START_FRAME_BYTES; i++) {
    _ledBuffer[idx++] = 0x00 ;
}
´´´
´´´
for(i=0; i<endFrameSize; i++)
    _ledBuffer[idx++] = 0x00 ;
´´´

instead of defining MIN and MAX, you should probably use std::min and std::max.

All in all, this seems to make it overly complicated, I don't see the reason for all of this.

**Comment by pcaffardi** [comment] 2015-08-10 14:44
hi! Sorry for too much code and macros, but i'm new to C++. I am an
assembly, C and java programmer, and i wrote the patch on the fly with nano
editor, without knowing so much on hyperion architecture.

About the end frame computation, my algorithm is using the minimum exact
number of bytes needed, all set to 0. With the first suggested patch i
always had last led flickering. With mine it does not happens, no matter
the number of leds count i configure in hyperion.

I know i'm using full brightness, but lower values can be used, too. when i
use hyperion in night-time, i always have to change the HUV value to reduce
the brightness. Since APA102 supports that parameter, it could be used
instead of transforming RGB values. but no problem if not: this is not an
issue, only a suggestion to let the driver handle the value.


Ciao,
Paolo Scaffardi
skype: pscaffardi
http://www.arsenio.net
http://www.sognilucidi.it

2015-08-10 16:29 GMT+02:00 mrgreywater <notifications@github.com>:

**Comment by pcaffardi** [comment] 2015-10-16 17:53
I tested last hyperion and same issue again: last led is wrong. This is my patch (source included: please merge it): http://www.arsenio.net/download/hyperion_apa102_patch.zip

**Comment by pmishev** [comment] 2016-01-20 20:52
I can confirm I'm having the same problem with the latest hyperion. I thought it might be related to the lack of a 3.3->5V line buffer (it worked without one, so I didn't bother adding it).
Are you planning on merging the fix?

**Comment by manzel** [comment] 2016-01-23 22:36
I can confirm the issue. And I have also added the line buffer, so that is not causing the problem. The patch by @pcaffardi worked, however.

**Comment by tpmodding** [comment] 2016-03-08 01:47
is this issue fixed with the new changes?

**Comment by brindosch** [comment] 2016-03-08 09:36
yes, end frame was fixed

Closed Thank you

**Closed by brindosch** 2016-03-08 09:36 UTC
