### ISSUE TITLE
V4L2 screenshot stuck

### ISSUE THREAD

**Issue by tarkah** [tvdzwan/hyperion#216] opened 2014-12-19 03:50 UTC
I have the STK1160 usb grabber and am running OpenELEC, the build from the lightberry.eu site that works with this grabber.  The grabber is recognized, but when I try to grab a screenshot, I get stuck... here is the output: 

```
OpenELEC:~ # LD_LIBRARY_PATH=/storage/hyperion/bin /storage/hyperion/bin/hyperio
n-v4l2 /storage/.config/hyperion.config.json --screenshot
V4L2 width=720 height=480
V4L2 pixel format=UYVY
V4L2 grabber signal threshold set to: {0,0,0}
V4L2 grabber started
```

And it just hangs there.  I have tried every possible configuration, NTSC vs PAL, different pixel formats, aspect rations, etc.  I've even used different versions of OpenELEC, but nothing.  The only thing I can think of is maybe my HDMI2AV device is not working.  I use the following device [HDMI2AV](http://www.amazon.com/Mini-Composite-Video-Audio-Converter/dp/B00K3OO5ZY/ref=cm_cr_pr_product_top) and it feels warm when I touch it (there is no led to indicate it is on).  Unfortunately I have no monitor with composite input to test it either.  

Has anyone experienced this issue and resolved it?  I've already had to buy 2 grabbers because my first was a Somagic chipset, so I really hope it isn't the grabber.  I have already tried plugging the grabber directly into my pi and a powered hub.  

I have not found any resolution to this... I am thinking it HAS to be a defective converter or grabber, as they are really the only two variables here.  Hopefully I am wrong though and someone has a solution.  Thanks!

**Comment by gskrills** [comment] 2015-01-11 03:45
I am having the exact same issue, and I have not found a resolution. Can anyone advise what the command line SHOULD output? currently I am seeing:

```

OpenELEC:~/.config # LD_LIBRARY_PATH=/storage/hyperion/bin /storage/hyperion/bin/hyperion-v4l2 --screenshot
V4L2 width=720 height=480
V4L2 pixel format=UYVY
V4L2 grabber signal threshold set to: {0,0,0}
V4L2 grabber started
```

And then it just hangs. I have checked the grabber on Win 7 and it works, as do all the other components. The problem is something software related I fear.

**Comment by hallard** [comment] 2015-01-21 13:36
Hi,
I had exactly the same issue, it was resolved by setting image format to NTSC (as the switch on the grabber), otherwise grabber seems to block the capture, don't know why but setting NTSC solved my problem

**Comment by gskrills** [comment] 2015-01-22 15:24
When you refer to the switch on the grabber, you are referring to the small PAL/NTSC switch on the HDMI/AV converter correct?

**Comment by hallard** [comment] 2015-01-22 16:25
Sorry, yes this switch AND also the one on command line for example
`hyperion-v4l2 -v NTSC`
and in configuration file it's
`
    "grabber-v4l2" :
    {
        "device" : "/dev/video0",
        "input" : 0,
        "standard" : "NTSC",
        "width" : -1,
        "height" :-1,
        "frameDecimation" : 2,
        "sizeDecimation" : 4,
        "priority" : 800,
        "mode" : "2D",
        "cropLeft" : 10,
        "cropRight" : 4,
        "cropTop" : 50,
        "cropBottom" : 4,
        "redSignalThreshold" : 0.1,
        "greenSignalThreshold" : 0.1,
        "blueSignalThreshold" : 0.1
    },
`

**Comment by evanluzi** [comment] 2015-01-27 06:38
I am having the same issue with the stk1160 USB grabber. Have confirmed the grabber is working on my iMac. Both the grabber and the HDMI2AV are connected to a powered USB hub. I am using the OpenElec image from lightberry. My HDMI2AV is set to NTSC and the config file is also set to NTSC.

When I give this command: `LD_LIBRARY_PATH=/storage/hyperion/bin /storage/hyperion/bin/hyperion-v4l2 --screenshot -v NTSC`

I get this response:

`V4L2 width=360 height=240
V4L2 pixel format=UYVY
V4L2 grabber signal threshold set to: {0,0,0}
V4L2 grabber started`

And then nothing. Please keep me updated if you find a solution!

**Comment by jlobue10** [comment] 2015-03-24 20:18
For those of you having this issue, I fixed mine by replacing the HDMI to AV converter. It seems the first one I ordered was faulty. After replacing it with a new one, I am up and running with my ambilight with PS4 as my source through V4L2. It runs very nicely through the RPi 2.

**Comment by broncodfw** [comment] 2015-04-05 02:32
hi all, I'm also having the same issue of Screenshot being stuck.
I'm using Openelec + Raspberry Pi 2 + STK1160 USB grabber, any insight on how to solve this issue would be amazing. I already went through a SoMagic USB grabber with no luck. 
Thanks in advance!

**Comment by jlobue10** [comment] 2015-04-05 02:43
Try replacing your HDMI to AV converter. That fixed the issue for me. You'll also want to power the USB grabber through a powered USB hub (plugged into an outlet), in order to make sure your grabber is getting enough power to function properly.

**Comment by broncodfw** [comment] 2015-04-05 03:13
Thanks jlobue10 for the quick response! Do you have Rpi2 and STK1160 as well?

**Comment by jlobue10** [comment] 2015-04-05 03:15
Yes, I am using that setup and got my project to work about two weeks ago using my PS4 as the video source.

**Comment by broncodfw** [comment] 2015-04-05 03:23
Great! Thanks for the input jlobue10, I was worried that the STK1160 is not supported for RPi2.

I currently have all the pieces in place, the LEDs work properly with Hyperion, and I can get the effects to work. Currently stuck at the screen-capture portion. Unfortunately the monitors I got at home do not support "yellow" component cable so I could not test the HDMI2AV converter.

**Comment by broncodfw** [comment] 2015-04-08 01:43
Hi jlobue10,
I currently added a USB HUB to my setup and using that to power the USB
STK1160 grabber.
Now, I the V4L2 screenshot stuck issue is gone ... but now i get the "Frame
too small" error.

Did you have any issue like that ? Do I need to use any modified STK1160
drivers ?

My setup
- OpenElec
- STK1160 USB Grabber
- USB Hub
- Raspberry Pi 2

Thanks!

**Comment by jlobue10** [comment] 2015-04-08 15:25
It seems that another user had this issue resolved here:

https://github.com/tvdzwan/hyperion/issues/12

by lowering the grabbing resolution. The picture will actually be pretty small, but it'll be enough to see that you have the edges lined up when you do the offsets.

**Comment by broncodfw** [comment] 2015-04-09 06:43
Thanks jlobue10 for the response. I still have no luck yet ... waiting on
the new HDMI2AV converter.

I have a noob question though, no matter what I resolution change in my
"hyperion-config.json" file, I dont see the change reflected when I run a
"screenshot" command :

For example:
1. My hyperion-config.json file is located in
 : \\192.168.137.203\Configfiles\hyperion.config.json
2. v4l2 grabber section in that file :

   "grabber-v4l2" :
    {
        "device" : "/dev/video0",
        "input" : 0,
        "standard" : "NTSC",
        "width" : 360,
        "height" : 288,
        "frameDecimation" : 4,
        "sizeDecimation" : 8,
        "priority" : 1100,
        "mode" : "2D",
        "cropLeft" : 26,
        "cropRight" : 27,
        "cropTop" : 20,
        "cropBottom" : 20,
        "redSignalThreshold" : 0.1,
        "greenSignalThreshold" : 0.1,
        "blueSignalThreshold" : 0.1
    },

"endOfJson" : "endOfJson"

3. Command that I send through Putty for screenshot :
LD_LIBRARY_PATH=/storage/hyperion/bin /storage/hyperion/bin/hyperion-v4l2
/storage/.config/hyperion.config.json --crop-top 0 --crop-bottom 0
--crop-left 0 --crop-right 0 --size-decimator 4 --frame-decimator 2
--screenshot

4. Output of V4L2 :

V4L2 width=720 height=480
V4L2 pixel format=UYVY
V4L2 grabber signal threshold set to: {0,0,0}
V4L2 grabber started


No matter what the Height/Width parameters I set in the .json file, the
output always shows 720x480 resolution. Is that expected?

Thanks!

**Comment by broncodfw** [comment] 2015-04-11 05:45
Hi jlobue10, I finally received a new HDMI2AV converter and I checked that
it is working properly. But still I'm having issues with the stuck V4L2
grabber.

Can you please let me know how you got the STK1160 working with Rpi2
Appreciate your help!

**Comment by jlobue10** [comment] 2015-04-11 15:45
I guess what I'd do is double check that the grabber is not faulty on a pc.

Also, how I got my setup to work on my Rpi2 was this:

I installed the Rpi2 image from this link:

http://lightberry.eu/#download

I then made sure that my config.txt and hyperion.config.json files were correctly configured and in the proper place on the SD card.

Lastly, I've been using updated images from here:

http://forum.kodi.tv/showthread.php?tid=211501

Just copy the tarball into the .update/ folder and reboot. I'd only do this last step once you have it working.

My config files for reference:

https://www.dropbox.com/s/pjo23l7u077hlrz/config.txt?dl=0
https://www.dropbox.com/s/i4zi83p9krw8j0u/hyperion.config.json?dl=0

**Comment by broncodfw** [comment] 2015-04-11 19:25
Great! Thank you jlobue10 I will use the lightberry images for Rpi2
(OpenElec 5.0.5 (Custom Build) with STK1160 support for RPi2) and let you
know

**Comment by broncodfw** [comment] 2015-04-11 20:54
Hi jobue10,

My USB STK1160 is working on a PC. But the frame rate is pretty crappy
though, it stutters. Is that normal ? When you check your STK1160 usb
grabber on a system, is the video really smooth ?

Thanks!

**Comment by broncodfw** [comment] 2015-04-12 02:10
Finally! Thanks jlobue10! The lightberry image works for stk1160 and Rpi2!
:)
I haven't checked the screenshot command as I fear it might make my stk1160
not work again :D

But, the lights change according to the source video. But, there is a delay
between the video and the led synchronization.
I'm using the WS2801 LED Strip. The delay is annoying ~1sec. Which
parameter fixes this issue?

Currently I set my frame and size decimator to 1

Thanks!

**Comment by broncodfw** [comment] 2015-04-12 02:17
Also, just wanted to let you know that I did not use the updated images
from your third link yet. I'm still using the lightberry image. Which
update version are you currently using?

Thanks

**Comment by jlobue10** [comment] 2015-04-12 02:22
I'm not sure what the exact cause of your delay is, but perhaps try different settings within the HyperCon.jar config file generator. I am no expert with all these settings, so I may have reached the limit in my ability to help you. I haven't updated or used my setup in a while since one of my LEDs became faulty and I haven't had the time to replace it (busy with schoolwork).

I would use the latest image, it looks like from the 9th of April. The builds are good and get better with each of his releases, in my experience. I'd try the update before you mess with the config file though.

**Comment by broncodfw** [comment] 2015-04-12 03:26
Cool thanks for all the info jlobue10!

**Comment by broncodfw** [comment] 2015-04-12 18:47
For folks who might have this issue of lag try the following settings, considerable lag is reduced for me : 

"Grabber V4L2": 
{ 
"device": "/ dev / Video0", 
"input": 0, 
"standard", "NTSC ", 
"width": 360, 
"height": 288, 
"frameDecimation": 1, 
"sizeDecimation": 1, 
"priority": 600, 
"fashion", "2D", 
"crop left": 12, 
"crop right": 12 
"CropTop": 12, 
"crop bottom": 20, 
"redSignalThreshold" 0.05, 
"greenSignalThreshold: 0.05, 
"blueSignalThreshold 's with 0.05 
},

**Comment by tpmodding** [comment] 2016-03-02 21:25
@tarkah can be closed?

**Comment by tarkah** [comment] 2016-03-03 16:20
Yes, thanks.

**Comment by NicoHood** [comment] 2016-03-03 16:24
@tarkah Please close the issue. We are not allowed to do that.

**Closed** 2016-03-05 23:01 UTC
