### ISSUE TITLE
Hyperion takes up a lot of CPU load with Kodi

### ISSUE THREAD

**Issue by BlueGene00** [tvdzwan/hyperion#236] opened 2015-01-17 16:50 UTC
Hello,

I have installed the newest Raspbmc (Kodi) and installed hyperion. But now I have the problem, that Hyperion is taking up a lot of CPU power, so using something else is impossible. 

Idle: about 20-30 % just for Hyperion
Control with App: + 15-25 % in addition

With the older version of Raspbmc, I did not had this problem.

![unbenannt](https://cloud.githubusercontent.com/assets/10575045/5789561/bc4ef0e6-9e70-11e4-85b9-c775db45b8bf.PNG)

**Comment by poljvd** [comment] 2015-01-18 18:00
That seems a bit much and I am not able to reproduce this behavior at the moment.. Are you still seeing these loads for Hyperion?

You are using the Raspbmc alpha version (released with Christmas)?
Can you share your config here?

**Comment by BlueGene00** [comment] 2015-01-18 18:57
Yes, I am using the Raspbmc alpha version from 24. December 2014 since it is the version which is installed, if you are using the Windows installer on the official Raspbmc website.

I also did a test with OSMC and the CPU load for Hyperion is also around 25-35%

I went back to Froyo Final (12.3) and I got the promised <3% (see screenshot).

Note: all tests are just the mainscreen of XBMC, without playing anything.

![frodo](https://cloud.githubusercontent.com/assets/10575045/5793628/9be07aa6-9f4b-11e4-974c-5ac258d9ae7c.PNG)


---------------------------------------------------------------
// Automatically generated configuration file for 'Hyperion daemon'
// Generated by: HyperCon (The Hyperion deamon configuration file builder

{
	/// Device configuration contains the following fields: 
	/// * 'name'       : The user friendly name of the device (only used for display purposes)
	/// * 'type'       : The type of the device or leds (known types for now are 'ws2801', 'ldp8806',
	///                  'lpd6803', 'sedu', 'adalight', 'lightpack', 'test' and 'none')
	/// * 'output'     : The output specification depends on selected device. This can for example be the
	///                  device specifier, device serial number, or the output file name
	/// * 'rate'       : The baudrate of the output to the device
	/// * 'colorOrder' : The order of the color bytes ('rgb', 'rbg', 'bgr', etc.).
	"device" :
	{
		"name"       : "MyPi",
		"type"       : "ws2801",
		"output"     : "/dev/spidev0.0",
		"rate"       : 250000,
		"colorOrder" : "bgr"
	},

	/// Color manipulation configuration used to tune the output colors to specific surroundings. 
	/// The configuration contains a list of color-transforms. Each transform contains the 
	/// following fields:
	///  * 'id'   : The unique identifier of the color transformation (eg 'device_1')	///  * 'leds' : The indices (or index ranges) of the leds to which this color transform applies
	///             (eg '0-5, 9, 11, 12-17'). The indices are zero based.	///  * 'hsv' : The manipulation in the Hue-Saturation-Value color domain with the following 
	///            tuning parameters:
	///            - 'saturationGain'  The gain adjustement of the saturation
	///            - 'valueGain'       The gain adjustement of the value
	///  * 'red'/'green'/'blue' : The manipulation in the Red-Green-Blue color domain with the 
	///                           following tuning parameters for each channel:
	///            - 'threshold'       The minimum required input value for the channel to be on 
	///                                (else zero)
	///            - 'gamma'           The gamma-curve correction factor
	///            - 'blacklevel'      The lowest possible value (when the channel is black)
	///            - 'whitelevel'      The highest possible value (when the channel is white)
	///
	/// Next to the list with color transforms there is also a smoothing option.
	///  * 'smoothing' : Smoothing of the colors in the time-domain with the following tuning 
	///                  parameters:
	///            - 'type'            The type of smoothing algorithm ('linear' or 'none')
	///            - 'time_ms'         The time constant for smoothing algorithm in milliseconds
	///            - 'updateFrequency' The update frequency of the leds in Hz
	"color" :
	{
		"transform" :
		[
			{
				"id"   : "default",
				"leds" : "*",
				"hsv" :
				{
					"saturationGain" : 8.0000,
					"valueGain"      : 8.0000
				},
				"red" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				},
				"green" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				},
				"blue" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				}
			}
		],
		"smoothing" :
		{
			"type"            : "linear",
			"time_ms"         : 100,
			"updateFrequency" : 40.0000
		}
	},

	///  The configuration for each individual led. This contains the specification of the area 
	///  averaged of an input image for each led to determine its color. Each item in the list 
	///  contains the following fields:
	///  * index: The index of the led. This determines its location in the string of leds; zero 
	///           being the first led.
	///  * hscan: The fractional part of the image along the horizontal used for the averaging 
	///           (minimum and maximum inclusive)
	///  * vscan: The fractional part of the image along the vertical used for the averaging 
	///           (minimum and maximum inclusive)
	"leds" : 
	[
		{
			"index" : 0,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.0323 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 1,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.0588 }
		},
		{
			"index" : 2,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.0588, "maximum" : 0.1176 }
		},
		{
			"index" : 3,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.1176, "maximum" : 0.1765 }
		},
		{
			"index" : 4,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.1765, "maximum" : 0.2353 }
		},
		{
			"index" : 5,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.2353, "maximum" : 0.2941 }
		},
		{
			"index" : 6,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.2941, "maximum" : 0.3529 }
		},
		{
			"index" : 7,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.3529, "maximum" : 0.4118 }
		},
		{
			"index" : 8,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.4118, "maximum" : 0.4706 }
		},
		{
			"index" : 9,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.4706, "maximum" : 0.5294 }
		},
		{
			"index" : 10,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.5294, "maximum" : 0.5882 }
		},
		{
			"index" : 11,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.5882, "maximum" : 0.6471 }
		},
		{
			"index" : 12,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.6471, "maximum" : 0.7059 }
		},
		{
			"index" : 13,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.7059, "maximum" : 0.7647 }
		},
		{
			"index" : 14,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.7647, "maximum" : 0.8235 }
		},
		{
			"index" : 15,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.8235, "maximum" : 0.8824 }
		},
		{
			"index" : 16,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.8824, "maximum" : 0.9412 }
		},
		{
			"index" : 17,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.9412, "maximum" : 1.0000 }
		},
		{
			"index" : 18,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.0323 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 19,
			"hscan" : { "minimum" : 0.0323, "maximum" : 0.0645 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 20,
			"hscan" : { "minimum" : 0.0645, "maximum" : 0.0968 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 21,
			"hscan" : { "minimum" : 0.0968, "maximum" : 0.1290 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 22,
			"hscan" : { "minimum" : 0.1290, "maximum" : 0.1613 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 23,
			"hscan" : { "minimum" : 0.1613, "maximum" : 0.1935 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 24,
			"hscan" : { "minimum" : 0.1935, "maximum" : 0.2258 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 25,
			"hscan" : { "minimum" : 0.2258, "maximum" : 0.2581 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 26,
			"hscan" : { "minimum" : 0.2581, "maximum" : 0.2903 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 27,
			"hscan" : { "minimum" : 0.2903, "maximum" : 0.3226 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 28,
			"hscan" : { "minimum" : 0.3226, "maximum" : 0.3548 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 29,
			"hscan" : { "minimum" : 0.3548, "maximum" : 0.3871 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 30,
			"hscan" : { "minimum" : 0.3871, "maximum" : 0.4194 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 31,
			"hscan" : { "minimum" : 0.4194, "maximum" : 0.4516 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 32,
			"hscan" : { "minimum" : 0.4516, "maximum" : 0.4839 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 33,
			"hscan" : { "minimum" : 0.4839, "maximum" : 0.5161 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 34,
			"hscan" : { "minimum" : 0.5161, "maximum" : 0.5484 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 35,
			"hscan" : { "minimum" : 0.5484, "maximum" : 0.5806 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 36,
			"hscan" : { "minimum" : 0.5806, "maximum" : 0.6129 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 37,
			"hscan" : { "minimum" : 0.6129, "maximum" : 0.6452 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 38,
			"hscan" : { "minimum" : 0.6452, "maximum" : 0.6774 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 39,
			"hscan" : { "minimum" : 0.6774, "maximum" : 0.7097 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 40,
			"hscan" : { "minimum" : 0.7097, "maximum" : 0.7419 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 41,
			"hscan" : { "minimum" : 0.7419, "maximum" : 0.7742 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 42,
			"hscan" : { "minimum" : 0.7742, "maximum" : 0.8065 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 43,
			"hscan" : { "minimum" : 0.8065, "maximum" : 0.8387 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 44,
			"hscan" : { "minimum" : 0.8387, "maximum" : 0.8710 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 45,
			"hscan" : { "minimum" : 0.8710, "maximum" : 0.9032 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 46,
			"hscan" : { "minimum" : 0.9032, "maximum" : 0.9355 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 47,
			"hscan" : { "minimum" : 0.9355, "maximum" : 0.9677 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 48,
			"hscan" : { "minimum" : 0.9677, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.8500, "maximum" : 1.0000 }
		},
		{
			"index" : 49,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.9412, "maximum" : 1.0000 }
		},
		{
			"index" : 50,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.8824, "maximum" : 0.9412 }
		},
		{
			"index" : 51,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.8235, "maximum" : 0.8824 }
		},
		{
			"index" : 52,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.7647, "maximum" : 0.8235 }
		},
		{
			"index" : 53,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.7059, "maximum" : 0.7647 }
		},
		{
			"index" : 54,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.6471, "maximum" : 0.7059 }
		},
		{
			"index" : 55,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.5882, "maximum" : 0.6471 }
		},
		{
			"index" : 56,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.5294, "maximum" : 0.5882 }
		},
		{
			"index" : 57,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.4706, "maximum" : 0.5294 }
		},
		{
			"index" : 58,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.4118, "maximum" : 0.4706 }
		},
		{
			"index" : 59,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.3529, "maximum" : 0.4118 }
		},
		{
			"index" : 60,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.2941, "maximum" : 0.3529 }
		},
		{
			"index" : 61,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.2353, "maximum" : 0.2941 }
		},
		{
			"index" : 62,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.1765, "maximum" : 0.2353 }
		},
		{
			"index" : 63,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.1176, "maximum" : 0.1765 }
		},
		{
			"index" : 64,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0588, "maximum" : 0.1176 }
		},
		{
			"index" : 65,
			"hscan" : { "minimum" : 0.9000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.0588 }
		},
		{
			"index" : 66,
			"hscan" : { "minimum" : 0.9677, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 67,
			"hscan" : { "minimum" : 0.9355, "maximum" : 0.9677 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 68,
			"hscan" : { "minimum" : 0.9032, "maximum" : 0.9355 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 69,
			"hscan" : { "minimum" : 0.8710, "maximum" : 0.9032 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 70,
			"hscan" : { "minimum" : 0.8387, "maximum" : 0.8710 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 71,
			"hscan" : { "minimum" : 0.8065, "maximum" : 0.8387 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 72,
			"hscan" : { "minimum" : 0.7742, "maximum" : 0.8065 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 73,
			"hscan" : { "minimum" : 0.7419, "maximum" : 0.7742 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 74,
			"hscan" : { "minimum" : 0.7097, "maximum" : 0.7419 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 75,
			"hscan" : { "minimum" : 0.6774, "maximum" : 0.7097 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 76,
			"hscan" : { "minimum" : 0.6452, "maximum" : 0.6774 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 77,
			"hscan" : { "minimum" : 0.6129, "maximum" : 0.6452 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 78,
			"hscan" : { "minimum" : 0.5806, "maximum" : 0.6129 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 79,
			"hscan" : { "minimum" : 0.5484, "maximum" : 0.5806 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 80,
			"hscan" : { "minimum" : 0.5161, "maximum" : 0.5484 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 81,
			"hscan" : { "minimum" : 0.4839, "maximum" : 0.5161 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 82,
			"hscan" : { "minimum" : 0.4516, "maximum" : 0.4839 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 83,
			"hscan" : { "minimum" : 0.4194, "maximum" : 0.4516 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 84,
			"hscan" : { "minimum" : 0.3871, "maximum" : 0.4194 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 85,
			"hscan" : { "minimum" : 0.3548, "maximum" : 0.3871 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 86,
			"hscan" : { "minimum" : 0.3226, "maximum" : 0.3548 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 87,
			"hscan" : { "minimum" : 0.2903, "maximum" : 0.3226 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 88,
			"hscan" : { "minimum" : 0.2581, "maximum" : 0.2903 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 89,
			"hscan" : { "minimum" : 0.2258, "maximum" : 0.2581 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 90,
			"hscan" : { "minimum" : 0.1935, "maximum" : 0.2258 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 91,
			"hscan" : { "minimum" : 0.1613, "maximum" : 0.1935 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 92,
			"hscan" : { "minimum" : 0.1290, "maximum" : 0.1613 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 93,
			"hscan" : { "minimum" : 0.0968, "maximum" : 0.1290 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 94,
			"hscan" : { "minimum" : 0.0645, "maximum" : 0.0968 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		},
		{
			"index" : 95,
			"hscan" : { "minimum" : 0.0323, "maximum" : 0.0645 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.1500 }
		}
	],

	/// The black border configuration, contains the following items: 
	///  * enable    : true if the detector should be activated
	///  * threshold : Value below which a pixel is regarded as black (value between 0.0 and 1.0)
	"blackborderdetector" : 
	{
		"enable" : true,
		"threshold" : 1.0
	},

	/// The configuration of the effect engine, contains the following items: 
	///  * paths        : An array with absolute location(s) of directories with effects 
	///  * bootsequence : The effect selected as 'boot sequence'
	"effects" : 
	{
		"paths" : 
		[
			"/opt/hyperion/effects"
		]
	},

	"bootsequence" : 
	{
		"effect" : "Rainbow swirl fast",
		"duration_ms" : 5000
	},

	///  The configuration for the frame-grabber, contains the following items: 
	///   * width        : The width of the grabbed frames [pixels]
	///   * height       : The height of the grabbed frames [pixels]
	///   * frequency_Hz : The frequency of the frame grab [Hz]
	"framegrabber" : 
	{
		"width" : 96,
		"height" : 64,
		"frequency_Hz" : 100.0
	},

	/// The configuration of the XBMC connection used to enable and disable the frame-grabber. Contains the following fields: 
	///  * xbmcAddress       : The IP address of the XBMC-host
	///  * xbmcTcpPort       : The TCP-port of the XBMC-server
	///  * grabVideo         : Flag indicating that the frame-grabber is on(true) during video playback
	///  * grabPictures      : Flag indicating that the frame-grabber is on(true) during picture show
	///  * grabAudio         : Flag indicating that the frame-grabber is on(true) during audio playback
	///  * grabMenu          : Flag indicating that the frame-grabber is on(true) in the XBMC menu
	///  * grabScreensaver   : Flag indicating that the frame-grabber is on(true) when XBMC is on screensaver
	///  * enable3DDetection : Flag indicating that the frame-grabber should switch to a 3D compatible modus if a 3D video is playing
	"xbmcVideoChecker" : 
	{
		"xbmcAddress" : "127.0.0.1",
		"xbmcTcpPort" : 9090,
		"grabVideo" : true,
		"grabPictures" : true,
		"grabAudio" : true,
		"grabMenu" : false,
		"grabScreensaver" : false,
		"enable3DDetection" : false
	},

	/// The configuration of the Json server which enables the json remote interface
	///  * port : Port at which the json server is started
	"jsonServer" : 
	{
		"port" : 19444
	},

	/// The configuration of the Proto server which enables the protobuffer remote interface
	///  * port : Port at which the protobuffer server is started
	"protoServer" : 
	{
		"port" : 19445
	},

	/// The configuration of the boblight server which enables the boblight remote interface
	///  * port : Port at which the boblight server is started
// 	"boblightServer" : 
// 	{
// 		"port" : 19333
// 	},

	"endOfJson" : "endOfJson"
}

**Comment by curunoir** [comment] 2015-02-24 10:01
Hi, I have an issue similar with newest RaspBMC but with he memory. When playing video the Kodi process consumes slowly all free memory until reboot. Do you also have this behaviour ? 

However the hyperiond cpu charge seems normal.

**Comment by BlueGene00** [comment] 2015-02-24 16:09
I have changed the values for frame grabber and smoothing and this problem is gone now.

You might also change to Raspberry Pi 2, which is working incredibly fast with OSMC.

**Comment by curunoir** [comment] 2015-02-24 16:50
Did you turn off frame grabber and smoothing ? Or else can I have your values ?

**Comment by BlueGene00** [comment] 2015-02-24 20:00
Frame grabber: 
width: 16
height:16
Interval: ms

Smooting:
time:100
Freq: 20

**Comment by bimsarck** [comment] 2015-03-07 16:19
I can confirm that the latest version of hyperion is using a lot of CPU.

-Video grabber(stk1160) as input with resolution 240x192
-RaspberryPi B with OpenELEC(Kernel 3.19)

latest hyperion version: CPU >30%
hyperion version from 09/2014: CPU < 11%

@poljvd,
why are the binarys from the last build not stripped?

.bimsarck

**Comment by tpmodding** [comment] 2016-03-02 21:18
@BlueGene00 think can be closed now?

**Comment by brindosch** [comment] 2016-03-08 00:11
Closed due to age. Please open a new one, if problems still exists.
Thank you

**Closed by brindosch** 2016-03-08 00:11 UTC
