### ISSUE TITLE
Install Hyperion on OpenElec x64

### ISSUE THREAD

**Issue by combl** [tvdzwan/hyperion#263] opened 2015-02-18 06:24 UTC
Hey there,

is it possible to install and run hyperion on my OpenElec x64 Installation? I got a Zotac ZBox ID41 and everything is runnig smooth with OpenElec. The only thing im missing is Hyperion. Boblight is running but hyperion is much better in my opinion.

So is there a way?

Thank you for your work!
Chris

**Comment by tvdzwan** [comment] 2015-03-02 19:28
I do not think there is an easy way of accomplishing this as there is no binary distribution of Hyperion for this platform. It would require getting the proper toolchain for the platform and building all the dependencies and Hyperion yourself.

**Comment by combl** [comment] 2015-03-03 11:31
So I was running Hyperion on my ID41 with kodibuntu before I switched to openelec. I could do a fresh install and get Hyperion running. But I need to know what files I should collect and transfer to openelec to get it running.

**Comment by tvdzwan** [comment] 2015-03-06 21:19
On the github under deploy is a file hyperion.deps.openelec-rpi.tar.gz, which contains all libraries required for OE on the RPi. The same list of files is (very likely) required for other OE installations. There could of course be version differences in the library versions on the RPi and on the ID41.

**Comment by b0mb** [comment] 2015-04-03 07:47
So did any get it working on zbox with openelec?

**Comment by BertusG** [comment] 2015-04-28 19:54
+1 for this, supporting x86 open elec will be a huge boost for hyperion under OpenElec users.

**Comment by Gamadril** [comment] 2015-05-10 00:28
Installed openelec_x64 on my old ion machine. Compiled hyperion on a debian x64 VM with -DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF -DENABLE_FB=ON and copied it with other missing libraries:
```
libQtNetwork.so.4
libXt.so.6
libICE.so.6
libSM.so.6
libaudio.so.2
hyperion-v4l2
libQtCore.so.4
libXau.so.6
libpng12.so.0
libQtGui.so.4
libXrender.so.1
```
and it seems to work...
If I find free time next week I'll send a pull request with a binary

**Comment by BertusG** [comment] 2015-05-11 09:26
Wow great work, I'm looking forward to see your hard work!

**Comment by b0mb** [comment] 2015-05-11 09:28
Would be really nice 😉
Am 11.05.2015 11:26 schrieb "BertusG" <notifications@github.com>:

**Comment by iLLiac4** [comment] 2015-05-16 06:21
There it is:
http://bite-in.com/hyperion/Hyperion_OpenELEC_x64.tgz

It is x64 build only. Extract it to /storage/hyperion and run with:
/storage/hyperion/bin/hyperiond.sh /storage/hyperion/config/hyperion.config.json


It is POC only so no autoran implemented yet.

**Comment by Gamadril** [comment] 2015-05-16 21:47
try it out:
```
curl -L -O https://raw.github.com/Gamadril/hyperion/master/bin/install_hyperion.sh
bash install_hyperion.sh
```

**Comment by cl4w** [comment] 2015-05-17 20:38
@Gamadril 

Hi!
I am also owner of a Zbox ID41. I'm looking for as well as combl to get Hyperion to run.

I recently bought the following system: AmbiLED HD. Although it runs with boblight ... but very slowly. I get 2-3 seconds delay - which looks really stupid ...

I have tested the script the following error occurred:

-rwxrwxrwx    1 root     root          5200 May 17 22:07 install_hyperion.sh


MediaPC:~ # /storage/install_hyperion.sh
Downloading hyperion
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7410k  100 7410k    0     0   122k      0  0:01:00  0:01:00 --:--:--  198k
Downloading missing openelec libraries
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0tar: invalid magic
tar: short read
curl: (23) Failed writing body (666 != 16384)

Sorry for the bad english! Try my best!

**Comment by Gamadril** [comment] 2015-05-17 21:18
sorry, forgot to redeploy the x64 binaries. Try it again.

**Comment by cl4w** [comment] 2015-05-18 18:15
Woohooo! Finally it works! 
The installation went well without any problems. 

The only thing I had to change was the parameter in the "autostart.sh" (/storage/.config/autostart.sh)

I changed:
/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json > /dev/null 2>&1 &

to: 

/storage/hyperion/bin/hyperiond.sh /storage/hyperion/config/hyperion.config.json > /dev/null 2>&1 &

thats all :) It works great!
Thank you very much Gamadril! :D

**Comment by b0mb** [comment] 2015-05-19 05:20
OpenELEC (official) Version: 5.95.1
OpenELEC:~ # curl -L -O 
https://raw.github.com/Gamadril/hyperion/master/bin/inst
all_hyperion.sh
   % Total    % Received % Xferd  Average Speed   Time    Time Time  Current
                                  Dload  Upload   Total   Spent Left  Speed
   0     0    0     0    0     0      0      0 --:--:-- --:--:-- 
--:--:--     0curl: (77) error setting certificate verify locations:
   CAfile: /etc/ssl/cacert.pem
   CApath: none

Hmmm...

Any1 can help plz?


Am 18.05.2015 um 20:15 schrieb cl4w:

**Comment by iLLiac4** [comment] 2015-05-19 05:27
This is bug with latest openelec 6.0 beta. It has already been fixed but you will have to wait for a new build.

**Comment by b0mb** [comment] 2015-05-19 05:28
OK

Thx for the info 😉
Am 19.05.2015 07:27 schrieb "iLLiac4" <notifications@github.com>:

**Comment by combl** [comment] 2015-05-23 22:15
Got it running too! Everything works like a charm. Even the iOS remote + effects. Big thanks!

**Comment by BertusG** [comment] 2015-09-03 12:57
Still very happy with this solution. Wondering why the topic isn't more popular, maybe it works in once for everybody :)

**Comment by BertusG** [comment] 2015-11-04 23:38
Unfortunately with the new OpenElec 6.0 I experience a lot of frame drops. Logs doesn't show anything useful, but without hyperion activated I don't experience any problems. So it has something to do with hyperion. More guys with similar problems?

**Comment by meowmoo** [comment] 2016-01-12 23:25
@Gamadril just found this old topic...and finally something that worked for me!  Thanks

would it be possible to get the x11 file also on your command?

**Comment by Gamadril** [comment] 2016-01-13 08:30
this one was intended for openelec. If you use x11 I guess you have a full linux distribution. Try to compile hyperion directly on your machine.

**Comment by meowmoo** [comment] 2016-01-13 11:13
@gamadril 
No, im using openelec on a chromebox. I like to have the ambilight an the kodi menu also, and I'm told that I need the x11 file to accomplish this.

**Comment by Gamadril** [comment] 2016-01-13 12:01
chromebox is a standard 64-bit x86 system, so the binary here should work out of the box. For video grabber activation for the menu is the config option `"grabMenu" : false`

**Comment by meowmoo** [comment] 2016-01-13 23:28
@Gamadril 

I tried it a good hour now, with official OE and an unofficial OE version, light are only on when starting a Video but never on the Menu

hyperion addon is installed

    "xbmcVideoChecker" : 
	{
		"xbmcAddress" : "127.0.0.1",
		"xbmcTcpPort" : 9090,
		"grabVideo" : true,
		"grabPictures" : true,
		"grabAudio" : true,
		"grabMenu" : true,
		"grabScreensaver" : true,
		"enable3DDetection" : true
	},    


did I still miss something? 

and since we pull hyperion from your git would be nice if you  aware of [xbmc/xbmc#8613 (comment)] (https://github.com/xbmc/xbmc/pull/8613#event-496601515)

looks like your much more active than tvdzwan :>

**Comment by iLLiac4** [comment] 2016-01-14 05:38
Try to take x-11 from mine zip http://bite-in.com/hyperion/Hyperion_OpenELEC_x64.tgz it should work.

**Comment by Gamadril** [comment] 2016-01-14 08:08
@meowmoo 
Make sure that the remote control interface is enabled: http://kodi.wiki/view/Settings/Services#Remote_control
the referenced issue should not affect my hyperion build since it's using /dev/fb0 directly regardless of the KODI API. As long as KODI will draw on the framebuffer, it will work.

**Comment by meowmoo** [comment] 2016-01-16 03:21
@Gamadril 
its turned on, still no luck.

the x11 file from iLLiac4 works fine, but if i upgrade to OE7 hyperion start flickering 

sticking with OE6 + your hyperoin and Illiac4's x11 file for now :D 

the kodi hyperion addon is also broken on OE7 so i guess i have to wait a bit more till all is fixed/settled

anyway thanks for the Help!

**Comment by iLLiac4** [comment] 2016-01-16 05:26
I think that framebuffer works on nvidia but not on intel as i have both devices and hyperion works only on nvidia one without addon but not on intel.

@Gamadril since you have knowledge can you clone git of the hyperion addon https://github.com/poljvd/script.service.hyperion and try to implement needed changes?

**Comment by bimsarck** [comment] 2016-01-20 20:18
here is the fixed version of hyperion addon for kodi v17:
copy and replace attached file(state.py)
```
cp state.py /storage/.kodi/addons/script.service.hyperion/resources/lib/
rm /storage/.kodi/addons/script.service.hyperion/resources/lib/state.pyo
```
then rebooting device or execute:
```
systemctl restart kodi
```

.bimsarck

[state.zip](https://github.com/tvdzwan/hyperion/files/98017/state.zip)

**Comment by iLLiac4** [comment] 2016-01-21 03:54
TNX it works. I have cloned repo and inserted your commits with your name as credits so more users will find it and can download it as addon.

**Comment by Freezli** [comment] 2016-01-27 00:42
I have every 30-40 sec a few skipped frames, 4-10, only with 24 and 23.976 Hz Video. TV and all other content works well, no skip, no drop. If I disable hyperiond, everything is ok, also when hyperiond is running and vertical sync is off, no problems, but the picture is very bad with Vsync off.

OE6, Arduino Uno R3, Zotac ID83 and the hyperion release from iLLiac4 from 16. May 2015

Someone has a hint or a solution?

**Comment by iLLiac4** [comment] 2016-01-27 04:32
Try release from gamadril.

**Comment by Freezli** [comment] 2016-01-27 11:29
I use the hyperiond, hyperion-remote and hyperion-v4l2 from the gamadril release, just a day younger then yours, but problem still exist.

I don't use the curl command, only downloaded the hyperion_x86_64.tar.gz.

My fastled.ino: http://pastebin.com/aCxDicE8

My hyperion.config.json: http://pastebin.com/XMYKi7J8

**Comment by Gamadril** [comment] 2016-01-27 12:43
sadly I don't have a system with Intel HD GPU which what I think might be the root of the problem to analyze it.

**Comment by Freezli** [comment] 2016-01-27 12:50
But why every ~40 sec?

**Comment by iLLiac4** [comment] 2016-01-27 13:23
Maybe bound rate in .ino file and config?  Which controller are you using?

**Comment by Freezli** [comment] 2016-01-27 13:27
Arduino UNO R3, China clone, baudrate 460800, somewhere i read about 500000, but is a strange value.

Higher or lower, what you suggest?

**Comment by Freezli** [comment] 2016-01-27 13:46
Which one? Create Adalight_FastLED_WS2812b_Mini_Pro_32u4.ino or 
Create Adalight_FastLED_WS2812b_Arduino_Nano.ino

Also try with WS2812b, what you mean exactly, try 2812 in my ino file or yours?

**Comment by iLLiac4** [comment] 2016-01-27 13:47
Adalight_FastLED_WS2812b_Arduino_Nano.ino
Read code in it. Change data pin and number of leds. and try 115200 bound rate.

**Comment by Freezli** [comment] 2016-01-27 17:37
After a few hours of testing still same problem, after 40 sec 4-8 skipped frames.

I tried different baudrates and LED types in your and my ino file, tried different hardware acceleration and renderer settings in OE, nothing helps. Updated to OE 6.0.1, no luck. killall hyperiond or disable vsync solve the problem, but the picture is unwatchable. Problem appears only on 24Hz content, all codecs.

Can someone provide a version for OE7, x64, so i can try a dev version?

**Comment by iLLiac4** [comment] 2016-01-27 17:41
http://forum.kodi.tv/showthread.php?tid=238393&page=52
Because of api changes you will need new addon atm available at:
https://github.com/iLLiac4/script.service.hyperion

**Comment by Freezli** [comment] 2016-01-27 18:00
Thank you, I will test with OpenELEC Krypton build #0122 and report back.

**Comment by Freezli** [comment] 2016-01-27 21:29
Problem solved. I tick the option "Sync playback to display" on in videosettings - playback, no skipped frames anymore so far. Never needed this option before, no skipped frames before using hyperion, but anyway, maybe this will helpful for others.

This thread, 4. posting gave me the hint, http://wetekforums.com/v/index.php?p=discussion/23149/23-976-playback?p=23219 <-- the 41 sec! I have a Panasonic Plasma STW60, and this device is capable to play 24Hz, so maybe there is a problem with grabbing 23.976 fps with 24 Hz output?

**Comment by EvilBuu** [comment] 2016-02-04 13:21
@iLLiac4 Hi there! Im having the same exact error on my ambilight setup with Philips hue. 

Im trying to make connect my Philips Bridge Heu to Rpi. Im using 2 Hyperion config daemons each running the Hues and the  apa102 ledstirp. 

This is the error: 

hyperiond: /home/pi/fix_do_apa/hyperion/dependencies/build/jsoncpp/json_value.cp                                                                                                                                                             p:1136: Json::Value& Json::Value::resolveReference(const char*, bool): Assertion                                                                                                                                                              `type_ == nullValue || type_ == objectValue' failed.

I think it has something to do with the hue bridge not connection to my rpi. If i change Ip output ro unreadable format for the birdge, the error does now show but putty session freezes and have to manually force quite. 

http://www.jsoneditoronline.org/?id=625aed6ec57b5c9f4a7c2b635bd811b2
Configs of hue and ledstrip
Can you make something out of this erorrcode?

**Comment by brindosch** [comment] 2016-03-07 22:40
@bimsarck 
@iLLiac4 
I merged the pull request
Thank you for contributing.

**Comment by brindosch** [comment] 2016-03-08 20:13
@iLLiac4 
DumpQ: I don´t own the philips hue, but why have you that strange username in it? I thought this have to be a name that is setting up at the bridge?

**Comment by iLLiac4** [comment] 2016-03-09 05:48
I do not get it? Which username?

**Comment by brindosch** [comment] 2016-03-09 20:27
/// Specific of Philips Hue: 
	/// * 'username'   : The name of user registred on the Philips Hue Bridge

**Comment by iLLiac4** [comment] 2016-03-10 05:12
I did not wrote that.

**Comment by brindosch** [comment] 2016-03-10 08:42
Seems a mess in my head ;)
@EvilBuu please read my comment :)

**Comment by brindosch** [comment] 2016-03-22 23:27
this is done, the new install script should all handle with OE x64 and x32

**Closed by brindosch** 2016-03-22 23:27 UTC
