### ISSUE TITLE
leds turning on on its own

### ISSUE THREAD

**Issue by v0d0r** [tvdzwan/hyperion#452] opened 2016-01-11 19:01 UTC
I have a strange issue with about half the leds turning on on its own after its been running idle.
Gets annoying in the middle of the night and it looks like daylight.  They turn off again when I restart the hyperion service. I am running lpd6803 lights.

Any idea what might be causing this?

**Comment by v0d0r** [comment] 2016-01-12 14:43
As a workaround I am going to try the following tonight.

* Have a cron run every minute and check if my Kodi is idle.
* If not idle do nothing
* If idle send blank lights via hyperion-remote.

cron for that attached below. will feedback it it works. 

==============
#!/bin/bash

if netstat -tulpen | egrep -q ':80.*kodi\.bin'; then
    IsIdle=$(curl -s -u xbmc:xbmc -X POST -H 'Content-type: application/json' -d '{"jsonrpc": "2.0", "method": "XBMC.GetInfoBooleans", "params": { "booleans": ["System.IdleTime(600) "] }, "id": 1}' http://localhost:80/jsonrpc)

   echo "IsIdle: $IsIdle"


    if [[ "$IsIdle" =~ true || "$IsIdle" =~ error ]]; then
echo "kodi is idle"
/usr/bin/hyperion-remote -c black -p 999

       exit 0
    else
        exit 1
    fi
    else
    # system not idle
    echo "kodi is not idle"
    exit 0
    fi
else
    exit 1
fi
==============

**Comment by v0d0r** [comment] 2016-01-13 17:32
Quick update. My hack cron seems to work perfectly. I added some logging just to confirm its running.
So this issue is not critical but obviously not ideal having a cron run every minute to switch it off when idle so any thoughts and suggestions still welcome.

cat check_lights.log 
Wed Jan 13 19:31:01 SAST 2016
Connected to localhost:19444
Set color to 0 0 0

**Comment by brindosch** [comment] 2016-02-16 15:36
@v0d0r 
The problem is "not" hyperion. The leds turning on due to the point, that the spi bus and others are very sensitive.
I could grab my data cable and the first leds are on, if no data is income.
Maybe it is possible to add "send black, if no picture is grabbed,kodi offline, no effects active" and so on
You are invited to build a good solution ;)

**Comment by redPanther** [comment] 2016-02-16 16:00
I think the best solution is to disconnect the power from the leds. If leds has its own power supply,  add a switch.

Want a smart solutions? Control your main power switch via raspi gpio.

**Comment by brindosch** [comment] 2016-02-16 16:40
I am using a master/slave socket with tv as master. Ok this is not that smart :)

**Comment by tpmodding** [comment] 2016-02-26 08:55
@v0d0r can be closed?

**Comment by v0d0r** [comment] 2016-02-26 11:58
Hi yes you can close it. Thanks for all the responses guys. I turned off hyperion daemon and the lights still went on from time to time. so in the end I just left the cron in place that sends black to the leds when kodi is idle. worse case it goes on for less than 60 seconds around once or twice a night but does not stay on..

**Comment by tpmodding** [comment] 2016-02-26 12:27
@v0d0r you must close it, i cant :)

**Closed** 2016-02-28 08:07 UTC
